# Generated by Django 5.2.15 on 2026-08-04 00:00

import uuid

from django.db import migrations, models


def backfill_workspace_ids(apps, schema_editor):
    Workspace = apps.get_model("db", "Workspace")
    audit_model = apps.get_model("db", "OperationGatewayAudit")
    idempotency_model = apps.get_model("db", "OperationGatewayIdempotency")
    workspace_ids = dict(Workspace.objects.values_list("slug", "id"))

    for model in (audit_model, idempotency_model):
        for record in model.objects.filter(workspace_id__isnull=True).only("id", "workspace_slug"):
            workspace_id = workspace_ids.get(record.workspace_slug)
            if workspace_id is not None:
                model.objects.filter(pk=record.pk).update(workspace_id=workspace_id)


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0123_operationgatewayaudit_operationgatewayidempotency"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationgatewayaudit",
            name="invocation_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="operationgatewayaudit",
            name="workspace_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="operationgatewayidempotency",
            name="invocation_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="operationgatewayidempotency",
            name="request_input",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="operationgatewayidempotency",
            name="retryable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="operationgatewayidempotency",
            name="workspace_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(backfill_workspace_ids, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="operationgatewayidempotency",
            name="operation_gateway_idempotency_key",
        ),
        migrations.AddConstraint(
            model_name="operationgatewayidempotency",
            constraint=models.UniqueConstraint(
                fields=("workspace_id", "caller_id", "operation_id", "idempotency_key"),
                name="operation_gateway_idempotency_key",
            ),
        ),
        migrations.AddIndex(
            model_name="operationgatewayidempotency",
            index=models.Index(fields=("workspace_id", "created_at"), name="op_gateway_workspace_created"),
        ),
        migrations.AddIndex(
            model_name="operationgatewayaudit",
            index=models.Index(fields=("workspace_id", "created_at"), name="op_gateway_audit_workspace_id"),
        ),
        migrations.AlterField(
            model_name="operationgatewayidempotency",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("denied", "Denied"),
                    ("failed_precommit", "Failed before commit"),
                    ("outcome_unknown", "Outcome unknown"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="operationgatewayaudit",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("intent", "Intent"),
                    ("success", "Success"),
                    ("denied", "Denied"),
                    ("failure", "Failure"),
                    ("outcome_unknown", "Outcome unknown"),
                    ("replay", "Replay"),
                ],
                max_length=32,
            ),
        ),
    ]
