# Generated by Django 5.2.15 on 2026-08-05

from django.db import migrations


FORWARD_SQL = r"""
CREATE OR REPLACE FUNCTION agent_guard_project_scope() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND NEW.workspace_id IS DISTINCT FROM OLD.workspace_id
       AND EXISTS (
           SELECT 1 FROM agent_actors WHERE project_id = NEW.id
           UNION ALL SELECT 1 FROM agent_profile_versions WHERE project_id = NEW.id
           UNION ALL SELECT 1 FROM agent_assignment_contracts WHERE project_id = NEW.id
           UNION ALL SELECT 1 FROM agent_run_attempts WHERE project_id = NEW.id
           UNION ALL SELECT 1 FROM agent_run_input_events WHERE project_id = NEW.id
           UNION ALL SELECT 1 FROM agent_runtime_invocations WHERE project_id = NEW.id
           UNION ALL SELECT 1 FROM agent_outcome_submissions WHERE project_id = NEW.id
           UNION ALL SELECT 1 FROM agent_run_terminal_events WHERE project_id = NEW.id
       ) THEN
        RAISE EXCEPTION 'A project with Plane Agent records cannot change workspace' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_actor_scope() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND (
        NEW.workspace_id IS DISTINCT FROM OLD.workspace_id OR
        NEW.project_id IS DISTINCT FROM OLD.project_id
    ) THEN
        RAISE EXCEPTION 'Agent actor workspace and project bindings are immutable' USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.project_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM projects p WHERE p.id = NEW.project_id AND p.workspace_id = NEW.workspace_id
    ) THEN
        RAISE EXCEPTION 'Agent actor project is outside its workspace' USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.active_profile_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM agent_profile_versions p
        WHERE p.id = NEW.active_profile_id AND p.actor_id = NEW.id
          AND p.workspace_id = NEW.workspace_id AND p.project_id IS NOT DISTINCT FROM NEW.project_id
    ) THEN
        RAISE EXCEPTION 'Agent active profile is outside its actor binding' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_scope() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    referenced_workspace uuid;
    referenced_project uuid;
    referenced_actor uuid;
    referenced_assignment uuid;
    referenced_run uuid;
BEGIN
    IF NEW.project_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM projects p WHERE p.id = NEW.project_id AND p.workspace_id = NEW.workspace_id
    ) THEN
        RAISE EXCEPTION 'Agent record project is outside its workspace' USING ERRCODE = 'check_violation';
    END IF;

    IF TG_TABLE_NAME = 'agent_profile_versions' THEN
        SELECT workspace_id, project_id INTO referenced_workspace, referenced_project
        FROM agent_actors WHERE id = NEW.actor_id;
        IF (referenced_workspace, referenced_project) IS DISTINCT FROM (NEW.workspace_id, NEW.project_id) THEN
            RAISE EXCEPTION 'Profile version must use its actor scope' USING ERRCODE = 'check_violation';
        END IF;
    ELSIF TG_TABLE_NAME = 'agent_assignment_contracts' THEN
        SELECT workspace_id, project_id INTO referenced_workspace, referenced_project
        FROM agent_actors WHERE id = NEW.assignee_id;
        IF referenced_workspace IS DISTINCT FROM NEW.workspace_id OR
           (referenced_project IS NOT NULL AND referenced_project IS DISTINCT FROM NEW.project_id) THEN
            RAISE EXCEPTION 'Assignment must use its assignee scope' USING ERRCODE = 'check_violation';
        END IF;
        IF NEW.lineage_of_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM agent_assignment_contracts a
            WHERE a.id = NEW.lineage_of_id AND a.workspace_id = NEW.workspace_id
              AND a.project_id IS NOT DISTINCT FROM NEW.project_id AND a.assignee_id = NEW.assignee_id
        ) THEN
            RAISE EXCEPTION 'Assignment lineage must use the same actor and scope' USING ERRCODE = 'check_violation';
        END IF;
    ELSIF TG_TABLE_NAME = 'agent_run_attempts' THEN
        SELECT workspace_id, project_id, assignee_id INTO referenced_workspace, referenced_project, referenced_actor
        FROM agent_assignment_contracts WHERE id = NEW.assignment_id;
        IF (referenced_workspace, referenced_project) IS DISTINCT FROM (NEW.workspace_id, NEW.project_id)
           OR referenced_actor IS DISTINCT FROM NEW.actor_id THEN
            RAISE EXCEPTION 'Run must use its assignment scope and assignee' USING ERRCODE = 'check_violation';
        END IF;
        SELECT workspace_id, project_id, actor_id INTO referenced_workspace, referenced_project, referenced_actor
        FROM agent_profile_versions WHERE id = NEW.profile_version_id;
        IF (referenced_workspace, referenced_project) IS DISTINCT FROM (NEW.workspace_id, NEW.project_id)
           OR referenced_actor IS DISTINCT FROM NEW.actor_id THEN
            RAISE EXCEPTION 'Run must use its actor profile scope' USING ERRCODE = 'check_violation';
        END IF;
        IF NEW.lineage_of_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM agent_run_attempts r
            WHERE r.id = NEW.lineage_of_id AND r.assignment_id = NEW.assignment_id
              AND r.workspace_id = NEW.workspace_id AND r.project_id IS NOT DISTINCT FROM NEW.project_id
        ) THEN
            RAISE EXCEPTION 'Run lineage must remain on the same assignment and scope'
                USING ERRCODE = 'check_violation';
        END IF;
        IF NEW.recovery_of_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM agent_run_attempts r
            WHERE r.id = NEW.recovery_of_id AND r.assignment_id = NEW.assignment_id
              AND r.workspace_id = NEW.workspace_id AND r.project_id IS NOT DISTINCT FROM NEW.project_id
              AND r.state = 'outcome_unknown'
        ) THEN
            RAISE EXCEPTION 'Run recovery must name an outcome-unknown run on the same assignment'
                USING ERRCODE = 'check_violation';
        END IF;
        IF NEW.recovery_intent IS NOT NULL AND NEW.recovery_of_id IS NULL THEN
            RAISE EXCEPTION 'Run recovery intent requires a recovery source' USING ERRCODE = 'check_violation';
        END IF;
    ELSIF TG_TABLE_NAME IN ('agent_run_input_events', 'agent_runtime_invocations', 'agent_outcome_submissions') THEN
        IF TG_TABLE_NAME = 'agent_run_input_events' OR TG_TABLE_NAME = 'agent_runtime_invocations' THEN
            referenced_run := NEW.run_id;
        ELSE
            referenced_run := NEW.run_id;
        END IF;
        SELECT workspace_id, project_id INTO referenced_workspace, referenced_project
        FROM agent_run_attempts WHERE id = referenced_run;
        IF (referenced_workspace, referenced_project) IS DISTINCT FROM (NEW.workspace_id, NEW.project_id) THEN
            RAISE EXCEPTION 'Agent child record must use its run scope' USING ERRCODE = 'check_violation';
        END IF;
        IF TG_TABLE_NAME = 'agent_outcome_submissions' THEN
            IF NEW.evaluator_id IS NOT NULL AND NOT EXISTS (
                SELECT 1 FROM agent_actors a
                WHERE a.id = NEW.evaluator_id AND a.workspace_id = NEW.workspace_id
                  AND (a.project_id IS NULL OR a.project_id IS NOT DISTINCT FROM NEW.project_id)
            ) THEN
                RAISE EXCEPTION 'Outcome evaluator is outside the outcome scope' USING ERRCODE = 'check_violation';
            END IF;
        END IF;
    ELSIF TG_TABLE_NAME = 'agent_run_terminal_events' THEN
        SELECT workspace_id, project_id, run_id INTO referenced_workspace, referenced_project, referenced_run
        FROM agent_runtime_invocations WHERE id = NEW.invocation_id;
        IF referenced_run IS DISTINCT FROM NEW.run_id
           OR (referenced_workspace, referenced_project) IS DISTINCT FROM (NEW.workspace_id, NEW.project_id)
           OR NOT EXISTS (
               SELECT 1 FROM agent_run_attempts r
               WHERE r.id = NEW.run_id
                 AND (r.workspace_id, r.project_id) IS NOT DISTINCT FROM (NEW.workspace_id, NEW.project_id)
           ) THEN
            RAISE EXCEPTION 'Terminal event must bind one invocation and its run scope'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_profile_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.workspace_id IS DISTINCT FROM OLD.workspace_id OR NEW.project_id IS DISTINCT FROM OLD.project_id
       OR NEW.actor_id IS DISTINCT FROM OLD.actor_id OR NEW.version IS DISTINCT FROM OLD.version
       OR NEW.display_name IS DISTINCT FROM OLD.display_name OR NEW.role IS DISTINCT FROM OLD.role
       OR NEW.persona IS DISTINCT FROM OLD.persona OR NEW.instructions IS DISTINCT FROM OLD.instructions
       OR NEW.expected_outcomes IS DISTINCT FROM OLD.expected_outcomes
       OR NEW.model_defaults IS DISTINCT FROM OLD.model_defaults
       OR NEW.runtime_defaults IS DISTINCT FROM OLD.runtime_defaults
       OR NEW.context_refs IS DISTINCT FROM OLD.context_refs
       OR NEW.tool_presentation IS DISTINCT FROM OLD.tool_presentation
       OR NEW.memory_scopes IS DISTINCT FROM OLD.memory_scopes THEN
        RAISE EXCEPTION 'ProfileVersion immutable fields cannot change' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_run_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.workspace_id IS DISTINCT FROM OLD.workspace_id OR NEW.project_id IS DISTINCT FROM OLD.project_id
       OR NEW.assignment_id IS DISTINCT FROM OLD.assignment_id OR NEW.actor_id IS DISTINCT FROM OLD.actor_id
       OR NEW.profile_version_id IS DISTINCT FROM OLD.profile_version_id OR NEW.snapshot IS DISTINCT FROM OLD.snapshot
       OR NEW.snapshot_content_digest IS DISTINCT FROM OLD.snapshot_content_digest
       OR NEW.creation_idempotency_key IS DISTINCT FROM OLD.creation_idempotency_key
       OR NEW.lineage_of_id IS DISTINCT FROM OLD.lineage_of_id OR NEW.lineage_reason IS DISTINCT FROM OLD.lineage_reason
       OR NEW.recovery_of_id IS DISTINCT FROM OLD.recovery_of_id
       OR NEW.recovery_intent IS DISTINCT FROM OLD.recovery_intent THEN
        RAISE EXCEPTION 'RunAttempt immutable snapshot and binding fields cannot change'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_run_lifecycle() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.invocation_count IS DISTINCT FROM OLD.invocation_count THEN
        IF NEW.invocation_count <> OLD.invocation_count + 1
           OR NEW.last_invocation_id IS NULL
           OR NOT EXISTS (
               SELECT 1 FROM agent_runtime_invocations i
               WHERE i.run_id = NEW.id AND i.invocation_id = NEW.last_invocation_id
           ) THEN
            RAISE EXCEPTION 'Run invocation lifecycle must advance one bound invocation at a time'
                USING ERRCODE = 'check_violation';
        END IF;
    ELSIF NEW.last_invocation_id IS DISTINCT FROM OLD.last_invocation_id
       OR NEW.cumulative_usage IS DISTINCT FROM OLD.cumulative_usage THEN
        RAISE EXCEPTION 'Run invocation binding and usage changes require a new invocation'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_input_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.workspace_id IS DISTINCT FROM OLD.workspace_id OR NEW.project_id IS DISTINCT FROM OLD.project_id
       OR NEW.run_id IS DISTINCT FROM OLD.run_id OR NEW.event_ref IS DISTINCT FROM OLD.event_ref
       OR NEW.kind IS DISTINCT FROM OLD.kind OR NEW.payload IS DISTINCT FROM OLD.payload
       OR NEW.payload_digest IS DISTINCT FROM OLD.payload_digest
       OR NEW.pending_input_ref IS DISTINCT FROM OLD.pending_input_ref
       OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key THEN
        RAISE EXCEPTION 'RunInputEvent immutable fields cannot change' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_invocation_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.workspace_id IS DISTINCT FROM OLD.workspace_id OR NEW.project_id IS DISTINCT FROM OLD.project_id
       OR NEW.run_id IS DISTINCT FROM OLD.run_id OR NEW.invocation_id IS DISTINCT FROM OLD.invocation_id
       OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key OR NEW.envelope IS DISTINCT FROM OLD.envelope THEN
        RAISE EXCEPTION 'RuntimeInvocation immutable binding and envelope fields cannot change'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_outcome_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.workspace_id IS DISTINCT FROM OLD.workspace_id OR NEW.project_id IS DISTINCT FROM OLD.project_id
       OR NEW.run_id IS DISTINCT FROM OLD.run_id OR NEW.summary IS DISTINCT FROM OLD.summary
       OR NEW.artifacts IS DISTINCT FROM OLD.artifacts OR NEW.evidence IS DISTINCT FROM OLD.evidence
       OR NEW.submission_idempotency_key IS DISTINCT FROM OLD.submission_idempotency_key THEN
        RAISE EXCEPTION 'OutcomeSubmission binding and submitted content cannot change'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_terminal_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'RunTerminalEvent is append-only' USING ERRCODE = 'check_violation';
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_assignment_state() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.state <> 'ready' THEN
            RAISE EXCEPTION 'Assignments must be created in ready state' USING ERRCODE = 'check_violation';
        END IF;
        RETURN NEW;
    END IF;
    IF NEW.revision IS DISTINCT FROM OLD.revision
       AND (NEW.revision <> OLD.revision + 1 OR NEW.state <> 'revision') THEN
        RAISE EXCEPTION 'Assignment revisions must advance exactly with a revision state'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.state = 'revision' AND NEW.revision = OLD.revision THEN
        RAISE EXCEPTION 'Assignment revision state must increment its revision' USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.state = OLD.state THEN RETURN NEW; END IF;
    IF NOT ((OLD.state = 'ready' AND NEW.state IN ('active', 'cancelled'))
        OR (OLD.state = 'active' AND NEW.state IN ('completed', 'revision', 'cancelled'))
        OR (OLD.state = 'revision' AND NEW.state IN ('active', 'cancelled'))) THEN
        RAISE EXCEPTION 'Illegal AssignmentContract state transition' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_run_state() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.state <> 'queued' THEN
            RAISE EXCEPTION 'Runs must be created in queued state' USING ERRCODE = 'check_violation';
        END IF;
        RETURN NEW;
    END IF;
    IF NEW.state = OLD.state THEN RETURN NEW; END IF;
    IF NOT (
        (OLD.state = 'queued' AND NEW.state IN ('running', 'failed', 'blocked', 'cancelled', 'outcome_unknown'))
        OR (OLD.state = 'running' AND NEW.state IN (
            'waiting_for_input', 'succeeded', 'failed', 'blocked', 'cancelled', 'outcome_unknown'
        ))
        OR (OLD.state = 'waiting_for_input' AND NEW.state IN (
            'running', 'succeeded', 'failed', 'blocked', 'cancelled', 'outcome_unknown'
        ))
    ) THEN
        RAISE EXCEPTION 'Illegal RunAttempt state transition' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_invocation_state() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.state NOT IN ('queued', 'running') THEN
            RAISE EXCEPTION 'Invocations must start in queued or running state' USING ERRCODE = 'check_violation';
        END IF;
        RETURN NEW;
    END IF;
    IF NEW.state = OLD.state THEN RETURN NEW; END IF;
    IF NOT (
        (OLD.state = 'queued' AND NEW.state = 'running')
        OR (OLD.state = 'running' AND NEW.state IN (
            'waiting_for_input', 'succeeded', 'failed', 'blocked', 'cancelled', 'outcome_unknown'
        ))
        OR (OLD.state = 'waiting_for_input' AND NEW.state IN (
            'running', 'succeeded', 'failed', 'blocked', 'cancelled', 'outcome_unknown'
        ))
    ) THEN
        RAISE EXCEPTION 'Illegal RuntimeInvocation state transition' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_outcome_state() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.state <> 'proposed' THEN
            RAISE EXCEPTION 'Outcomes must be created in proposed state' USING ERRCODE = 'check_violation';
        END IF;
        RETURN NEW;
    END IF;
    IF NEW.state = OLD.state THEN RETURN NEW; END IF;
    IF NOT ((OLD.state = 'proposed' AND NEW.state = 'evaluator_reviewed')
        OR (OLD.state = 'evaluator_reviewed' AND NEW.state IN ('accepted', 'revision_requested'))) THEN
        RAISE EXCEPTION 'Illegal OutcomeSubmission state transition' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_check_assignment_terminal() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.state = 'completed' AND NOT EXISTS (
        SELECT 1 FROM agent_run_attempts r JOIN agent_outcome_submissions o ON o.run_id = r.id
        WHERE r.assignment_id = NEW.id AND o.state = 'accepted'
    ) THEN
        RAISE EXCEPTION 'Completed assignments require an accepted outcome' USING ERRCODE = 'check_violation';
    ELSIF NEW.state = 'revision' AND NOT EXISTS (
        SELECT 1 FROM agent_run_attempts r JOIN agent_outcome_submissions o ON o.run_id = r.id
        WHERE r.assignment_id = NEW.id AND o.state = 'revision_requested'
    ) THEN
        RAISE EXCEPTION 'Revised assignments require a revision-requested outcome' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION agent_check_run_terminal() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.state IN ('succeeded', 'failed', 'blocked', 'cancelled') AND NOT EXISTS (
        SELECT 1 FROM agent_runtime_invocations i
        JOIN agent_run_terminal_events e ON e.invocation_id = i.id
        WHERE i.run_id = NEW.id AND e.run_id = NEW.id
          AND i.invocation_id IS NOT DISTINCT FROM NEW.last_invocation_id
    ) THEN
        RAISE EXCEPTION 'Terminal runs require a matching visible terminal event' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION agent_check_invocation_terminal() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.state IN ('succeeded', 'failed', 'blocked', 'cancelled') AND NOT EXISTS (
        SELECT 1 FROM agent_run_terminal_events e WHERE e.invocation_id = NEW.id AND e.run_id = NEW.run_id
    ) THEN
        RAISE EXCEPTION 'Terminal invocations require a matching visible terminal event'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION agent_check_outcome_terminal() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.state IN ('accepted', 'revision_requested') AND (
        NEW.evaluator_id IS NULL OR NEW.evaluator_reviewed_at IS NULL
        OR NEW.human_reviewer_id IS NULL OR NEW.human_decided_at IS NULL
        OR NOT EXISTS (
            SELECT 1 FROM agent_run_attempts r
            JOIN agent_run_terminal_events e ON e.run_id = r.id
            JOIN agent_runtime_invocations i ON i.id = e.invocation_id
            WHERE r.id = NEW.run_id AND r.state = 'succeeded'
              AND i.state = 'succeeded' AND e.kind = 'outcome_submission'
        )
    ) THEN
        RAISE EXCEPTION 'Final outcome decisions require review fields and a succeeded run'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_terminal_event() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    invocation_state text;
    run_state text;
BEGIN
    IF NEW.visible IS NOT TRUE THEN
        RAISE EXCEPTION 'Terminal events must be visible Plane product events' USING ERRCODE = 'check_violation';
    END IF;
    SELECT state INTO invocation_state FROM agent_runtime_invocations WHERE id = NEW.invocation_id;
    SELECT state INTO run_state FROM agent_run_attempts WHERE id = NEW.run_id;
    IF (NEW.kind = 'outcome_submission' AND (invocation_state <> 'succeeded' OR run_state <> 'succeeded'))
       OR (NEW.kind = 'run_failure' AND (invocation_state <> 'failed' OR run_state <> 'failed'))
       OR (NEW.kind = 'run_blocker' AND (invocation_state <> 'blocked' OR run_state <> 'blocked'))
       OR (NEW.kind = 'run_cancellation' AND (invocation_state <> 'cancelled' OR run_state <> 'cancelled')) THEN
        RAISE EXCEPTION 'Terminal event kind does not match its invocation and run states'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.kind = 'outcome_submission' AND NOT EXISTS (
        SELECT 1 FROM agent_outcome_submissions o
        WHERE o.run_id = NEW.run_id AND NEW.product_ref = 'outcome-submission:' || o.id::text
    ) THEN
        RAISE EXCEPTION 'Outcome terminal event must identify its submitted outcome' USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.kind <> 'outcome_submission' AND NEW.product_ref IS DISTINCT FROM NEW.product_event_ref THEN
        RAISE EXCEPTION 'Supervisor terminal product refs must equal their product event refs'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.kind = 'run_cancellation' AND NEW.cancellation_ref IS NULL THEN
        RAISE EXCEPTION 'Cancellation terminal events require a cancellation reference'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER agent_projects_scope_guard BEFORE UPDATE OF workspace_id ON projects
FOR EACH ROW EXECUTE FUNCTION agent_guard_project_scope();
CREATE TRIGGER agent_actor_scope_guard BEFORE INSERT OR UPDATE ON agent_actors
FOR EACH ROW EXECUTE FUNCTION agent_guard_actor_scope();

CREATE TRIGGER agent_profile_scope_guard BEFORE INSERT OR UPDATE ON agent_profile_versions
FOR EACH ROW EXECUTE FUNCTION agent_guard_scope();
CREATE TRIGGER agent_assignment_scope_guard BEFORE INSERT OR UPDATE ON agent_assignment_contracts
FOR EACH ROW EXECUTE FUNCTION agent_guard_scope();
CREATE TRIGGER agent_run_scope_guard BEFORE INSERT OR UPDATE ON agent_run_attempts
FOR EACH ROW EXECUTE FUNCTION agent_guard_scope();
CREATE TRIGGER agent_input_scope_guard BEFORE INSERT OR UPDATE ON agent_run_input_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_scope();
CREATE TRIGGER agent_invocation_scope_guard BEFORE INSERT OR UPDATE ON agent_runtime_invocations
FOR EACH ROW EXECUTE FUNCTION agent_guard_scope();
CREATE TRIGGER agent_outcome_scope_guard BEFORE INSERT OR UPDATE ON agent_outcome_submissions
FOR EACH ROW EXECUTE FUNCTION agent_guard_scope();
CREATE TRIGGER agent_terminal_scope_guard BEFORE INSERT ON agent_run_terminal_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_scope();

CREATE TRIGGER agent_profile_immutable_guard BEFORE UPDATE ON agent_profile_versions
FOR EACH ROW EXECUTE FUNCTION agent_guard_profile_immutable();
CREATE TRIGGER agent_run_immutable_guard BEFORE UPDATE ON agent_run_attempts
FOR EACH ROW EXECUTE FUNCTION agent_guard_run_immutable();
CREATE TRIGGER agent_run_lifecycle_guard BEFORE UPDATE ON agent_run_attempts
FOR EACH ROW EXECUTE FUNCTION agent_guard_run_lifecycle();
CREATE TRIGGER agent_input_immutable_guard BEFORE UPDATE ON agent_run_input_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_input_immutable();
CREATE TRIGGER agent_invocation_immutable_guard BEFORE UPDATE ON agent_runtime_invocations
FOR EACH ROW EXECUTE FUNCTION agent_guard_invocation_immutable();
CREATE TRIGGER agent_outcome_immutable_guard BEFORE UPDATE ON agent_outcome_submissions
FOR EACH ROW EXECUTE FUNCTION agent_guard_outcome_immutable();
CREATE TRIGGER agent_terminal_append_guard BEFORE UPDATE OR DELETE ON agent_run_terminal_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_terminal_append_only();

CREATE TRIGGER agent_assignment_state_guard BEFORE INSERT OR UPDATE OF state ON agent_assignment_contracts
FOR EACH ROW EXECUTE FUNCTION agent_guard_assignment_state();
CREATE TRIGGER agent_run_state_guard BEFORE INSERT OR UPDATE OF state ON agent_run_attempts
FOR EACH ROW EXECUTE FUNCTION agent_guard_run_state();
CREATE TRIGGER agent_invocation_state_guard BEFORE INSERT OR UPDATE OF state ON agent_runtime_invocations
FOR EACH ROW EXECUTE FUNCTION agent_guard_invocation_state();
CREATE TRIGGER agent_outcome_state_guard BEFORE INSERT OR UPDATE OF state ON agent_outcome_submissions
FOR EACH ROW EXECUTE FUNCTION agent_guard_outcome_state();

CREATE CONSTRAINT TRIGGER agent_assignment_terminal_check
AFTER INSERT OR UPDATE ON agent_assignment_contracts DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION agent_check_assignment_terminal();
CREATE CONSTRAINT TRIGGER agent_run_terminal_check
AFTER INSERT OR UPDATE ON agent_run_attempts DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION agent_check_run_terminal();
CREATE CONSTRAINT TRIGGER agent_invocation_terminal_check
AFTER INSERT OR UPDATE ON agent_runtime_invocations DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION agent_check_invocation_terminal();
CREATE CONSTRAINT TRIGGER agent_outcome_terminal_check
AFTER INSERT OR UPDATE ON agent_outcome_submissions DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION agent_check_outcome_terminal();
CREATE TRIGGER agent_terminal_event_guard BEFORE INSERT ON agent_run_terminal_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_terminal_event();
"""


REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS agent_terminal_event_guard ON agent_run_terminal_events;
DROP TRIGGER IF EXISTS agent_outcome_terminal_check ON agent_outcome_submissions;
DROP TRIGGER IF EXISTS agent_invocation_terminal_check ON agent_runtime_invocations;
DROP TRIGGER IF EXISTS agent_run_terminal_check ON agent_run_attempts;
DROP TRIGGER IF EXISTS agent_assignment_terminal_check ON agent_assignment_contracts;
DROP TRIGGER IF EXISTS agent_outcome_state_guard ON agent_outcome_submissions;
DROP TRIGGER IF EXISTS agent_invocation_state_guard ON agent_runtime_invocations;
DROP TRIGGER IF EXISTS agent_run_state_guard ON agent_run_attempts;
DROP TRIGGER IF EXISTS agent_assignment_state_guard ON agent_assignment_contracts;
DROP TRIGGER IF EXISTS agent_terminal_append_guard ON agent_run_terminal_events;
DROP TRIGGER IF EXISTS agent_outcome_immutable_guard ON agent_outcome_submissions;
DROP TRIGGER IF EXISTS agent_invocation_immutable_guard ON agent_runtime_invocations;
DROP TRIGGER IF EXISTS agent_input_immutable_guard ON agent_run_input_events;
DROP TRIGGER IF EXISTS agent_run_immutable_guard ON agent_run_attempts;
DROP TRIGGER IF EXISTS agent_run_lifecycle_guard ON agent_run_attempts;
DROP TRIGGER IF EXISTS agent_profile_immutable_guard ON agent_profile_versions;
DROP TRIGGER IF EXISTS agent_terminal_scope_guard ON agent_run_terminal_events;
DROP TRIGGER IF EXISTS agent_outcome_scope_guard ON agent_outcome_submissions;
DROP TRIGGER IF EXISTS agent_invocation_scope_guard ON agent_runtime_invocations;
DROP TRIGGER IF EXISTS agent_input_scope_guard ON agent_run_input_events;
DROP TRIGGER IF EXISTS agent_run_scope_guard ON agent_run_attempts;
DROP TRIGGER IF EXISTS agent_assignment_scope_guard ON agent_assignment_contracts;
DROP TRIGGER IF EXISTS agent_profile_scope_guard ON agent_profile_versions;
DROP TRIGGER IF EXISTS agent_actor_scope_guard ON agent_actors;
DROP TRIGGER IF EXISTS agent_projects_scope_guard ON projects;
DROP FUNCTION IF EXISTS agent_guard_terminal_event();
DROP FUNCTION IF EXISTS agent_check_outcome_terminal();
DROP FUNCTION IF EXISTS agent_check_invocation_terminal();
DROP FUNCTION IF EXISTS agent_check_run_terminal();
DROP FUNCTION IF EXISTS agent_check_assignment_terminal();
DROP FUNCTION IF EXISTS agent_guard_outcome_state();
DROP FUNCTION IF EXISTS agent_guard_invocation_state();
DROP FUNCTION IF EXISTS agent_guard_run_state();
DROP FUNCTION IF EXISTS agent_guard_assignment_state();
DROP FUNCTION IF EXISTS agent_guard_terminal_append_only();
DROP FUNCTION IF EXISTS agent_guard_outcome_immutable();
DROP FUNCTION IF EXISTS agent_guard_invocation_immutable();
DROP FUNCTION IF EXISTS agent_guard_input_immutable();
DROP FUNCTION IF EXISTS agent_guard_run_immutable();
DROP FUNCTION IF EXISTS agent_guard_run_lifecycle();
DROP FUNCTION IF EXISTS agent_guard_profile_immutable();
DROP FUNCTION IF EXISTS agent_guard_scope();
DROP FUNCTION IF EXISTS agent_guard_actor_scope();
DROP FUNCTION IF EXISTS agent_guard_project_scope();
"""


class Migration(migrations.Migration):
    dependencies = [("db", "0123_agent_lifecycle_foundation")]

    operations = [migrations.RunSQL(FORWARD_SQL, REVERSE_SQL)]
