# Generated by Django 5.2.15 on 2026-08-04

from django.db import migrations, models
import django.db.models.deletion
import uuid


CREATE_AUDIT_TRIGGER = """
CREATE OR REPLACE FUNCTION operation_gateway_audit_append_only()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'operation gateway audit records are append-only'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER operation_gateway_audit_append_only_trigger
BEFORE UPDATE OR DELETE ON operation_gateway_audit
FOR EACH ROW
EXECUTE FUNCTION operation_gateway_audit_append_only();

REVOKE ALL ON FUNCTION operation_gateway_audit_append_only() FROM PUBLIC;
"""

DROP_AUDIT_TRIGGER = """
DROP TRIGGER IF EXISTS operation_gateway_audit_append_only_trigger ON operation_gateway_audit;
DROP FUNCTION IF EXISTS operation_gateway_audit_append_only();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0124_operationgateway_hardening"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationGatewayPublication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("invocation_id", models.UUIDField(editable=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("activity", "Activity"),
                            ("notification", "Notification"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=32,
                    ),
                ),
                ("publication_key", models.CharField(editable=False, max_length=160, unique=True)),
                ("payload", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, default="", max_length=255)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "idempotency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publications",
                        to="db.operationgatewayidempotency",
                    ),
                ),
            ],
            options={
                "db_table": "operation_gateway_publication",
                "indexes": [
                    models.Index(fields=("state", "lease_until"), name="op_gateway_pub_dispatch"),
                    models.Index(fields=("idempotency", "created_at"), name="op_gateway_pub_attempt"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("idempotency", "kind"),
                        name="operation_gateway_publication_kind",
                    )
                ],
            },
        ),
        migrations.RunSQL(CREATE_AUDIT_TRIGGER, DROP_AUDIT_TRIGGER),
        migrations.AlterModelOptions(
            name="operationgatewayaudit",
            options={
                "base_manager_name": "objects",
                "db_table": "operation_gateway_audit",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(fields=("workspace_id", "created_at"), name="op_gateway_audit_workspace_id"),
                    models.Index(fields=("workspace_slug", "created_at"), name="op_gateway_audit_workspace"),
                    models.Index(fields=("caller_id", "created_at"), name="op_gateway_audit_caller"),
                ],
                "ordering": ("created_at", "id"),
            },
        ),
    ]
