# Generated by Django 5.2.15 on 2026-08-05

import plane.db.models.agent
from django.db import migrations, models


BACKFILL_SQL = r"""
WITH ranked AS (
    SELECT id, row_number() OVER (PARTITION BY run_id ORDER BY created_at, id) AS ordinal
    FROM agent_runtime_invocations
)
UPDATE agent_runtime_invocations AS i
SET ordinal = ranked.ordinal
FROM ranked
WHERE i.id = ranked.id;

UPDATE agent_runtime_invocations AS i
SET usage = r.cumulative_usage
FROM agent_run_attempts AS r
WHERE i.run_id = r.id AND i.invocation_id = r.last_invocation_id;
"""


FORWARD_SQL = r"""
CREATE OR REPLACE FUNCTION agent_guard_assignment_commission_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        PERFORM 1 FROM agent_assignment_contracts WHERE id = OLD.id FOR UPDATE;
        IF EXISTS (SELECT 1 FROM agent_run_attempts WHERE assignment_id = OLD.id)
           AND (
               NEW.workspace_id IS DISTINCT FROM OLD.workspace_id
               OR NEW.project_id IS DISTINCT FROM OLD.project_id
               OR NEW.assignee_id IS DISTINCT FROM OLD.assignee_id
               OR NEW.lineage_of_id IS DISTINCT FROM OLD.lineage_of_id
               OR NEW.target_ref IS DISTINCT FROM OLD.target_ref
               OR NEW.objective IS DISTINCT FROM OLD.objective
               OR NEW.acceptance_criteria IS DISTINCT FROM OLD.acceptance_criteria
               OR NEW.context_refs IS DISTINCT FROM OLD.context_refs
           ) THEN
            RAISE EXCEPTION 'Assignment commission is immutable after execution begins'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_lock_assignment_for_run() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    PERFORM 1 FROM agent_assignment_contracts WHERE id = NEW.assignment_id FOR KEY SHARE;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_command_fingerprint_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.command_fingerprint IS DISTINCT FROM OLD.command_fingerprint THEN
        RAISE EXCEPTION 'Idempotent command fingerprints are immutable' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_invocation_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'RuntimeInvocation is append-only' USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.ordinal IS DISTINCT FROM OLD.ordinal OR NEW.usage IS DISTINCT FROM OLD.usage THEN
        RAISE EXCEPTION 'RuntimeInvocation ordinal and usage are immutable' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_invocation_progress() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    current_count integer;
    usage_field text;
BEGIN
    SELECT invocation_count INTO current_count
    FROM agent_run_attempts
    WHERE id = NEW.run_id
    FOR UPDATE;
    IF current_count IS NULL OR NEW.ordinal <> current_count + 1 THEN
        RAISE EXCEPTION 'RuntimeInvocation ordinal must be the next run ordinal'
            USING ERRCODE = 'check_violation';
    END IF;
    IF jsonb_typeof(NEW.usage) IS DISTINCT FROM 'object'
       OR NOT (NEW.usage ?& ARRAY['inputTokens', 'outputTokens', 'durationMs'])
       OR (SELECT count(*) FROM jsonb_object_keys(NEW.usage)) <> 3 THEN
        RAISE EXCEPTION 'RuntimeInvocation usage must contain exactly the accepted counters'
            USING ERRCODE = 'check_violation';
    END IF;
    FOREACH usage_field IN ARRAY ARRAY['inputTokens', 'outputTokens', 'durationMs'] LOOP
        IF jsonb_typeof(NEW.usage -> usage_field) <> 'number'
           OR (NEW.usage ->> usage_field)::numeric < 0
           OR (NEW.usage ->> usage_field)::numeric > 2147483647
           OR (NEW.usage ->> usage_field)::numeric <> trunc((NEW.usage ->> usage_field)::numeric) THEN
            RAISE EXCEPTION 'RuntimeInvocation usage counters must be bounded non-negative integers'
                USING ERRCODE = 'check_violation';
        END IF;
    END LOOP;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_check_run_invocation_aggregate() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    checked_run uuid;
    expected_count integer;
    expected_last text;
    expected_usage jsonb;
    actual_count integer;
    actual_usage jsonb;
BEGIN
    IF TG_TABLE_NAME = 'agent_runtime_invocations' THEN
        IF TG_OP = 'DELETE' THEN
            checked_run := OLD.run_id;
        ELSE
            checked_run := NEW.run_id;
        END IF;
    ELSE
        checked_run := NEW.id;
    END IF;
    SELECT invocation_count, last_invocation_id, cumulative_usage
    INTO expected_count, expected_last, expected_usage
    FROM agent_run_attempts
    WHERE id = checked_run;
    SELECT count(*)::integer,
           jsonb_build_object(
               'inputTokens', COALESCE(sum((usage ->> 'inputTokens')::bigint), 0),
               'outputTokens', COALESCE(sum((usage ->> 'outputTokens')::bigint), 0),
               'durationMs', COALESCE(sum((usage ->> 'durationMs')::bigint), 0)
           )
    INTO actual_count, actual_usage
    FROM agent_runtime_invocations
    WHERE run_id = checked_run;
    IF expected_count IS NULL
       OR expected_count <> actual_count
       OR expected_usage IS DISTINCT FROM actual_usage
       OR (expected_count = 0 AND expected_last IS NOT NULL)
       OR (expected_count > 0 AND NOT EXISTS (
           SELECT 1 FROM agent_runtime_invocations
           WHERE run_id = checked_run AND ordinal = expected_count
             AND invocation_id = expected_last
       )) THEN
        RAISE EXCEPTION 'Run invocation count and cumulative usage must equal the invocation aggregate'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END;
$$;

CREATE TRIGGER agent_assignment_commission_guard
BEFORE UPDATE ON agent_assignment_contracts
FOR EACH ROW EXECUTE FUNCTION agent_guard_assignment_commission_immutable();
CREATE TRIGGER agent_run_assignment_lock
BEFORE INSERT ON agent_run_attempts
FOR EACH ROW EXECUTE FUNCTION agent_lock_assignment_for_run();

CREATE TRIGGER agent_run_command_fingerprint_guard
BEFORE UPDATE ON agent_run_attempts
FOR EACH ROW EXECUTE FUNCTION agent_guard_command_fingerprint_immutable();
CREATE TRIGGER agent_input_command_fingerprint_guard
BEFORE UPDATE ON agent_run_input_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_command_fingerprint_immutable();
CREATE TRIGGER agent_invocation_command_fingerprint_guard
BEFORE UPDATE ON agent_runtime_invocations
FOR EACH ROW EXECUTE FUNCTION agent_guard_command_fingerprint_immutable();
CREATE TRIGGER agent_outcome_command_fingerprint_guard
BEFORE UPDATE ON agent_outcome_submissions
FOR EACH ROW EXECUTE FUNCTION agent_guard_command_fingerprint_immutable();
CREATE TRIGGER agent_terminal_command_fingerprint_guard
BEFORE UPDATE ON agent_run_terminal_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_command_fingerprint_immutable();

CREATE TRIGGER agent_invocation_append_guard
BEFORE UPDATE OR DELETE ON agent_runtime_invocations
FOR EACH ROW EXECUTE FUNCTION agent_guard_invocation_append_only();
CREATE TRIGGER agent_invocation_progress_guard
BEFORE INSERT ON agent_runtime_invocations
FOR EACH ROW EXECUTE FUNCTION agent_guard_invocation_progress();

CREATE CONSTRAINT TRIGGER agent_run_invocation_aggregate_check
AFTER INSERT OR UPDATE OF invocation_count, last_invocation_id, cumulative_usage ON agent_run_attempts
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION agent_check_run_invocation_aggregate();
CREATE CONSTRAINT TRIGGER agent_invocation_aggregate_check
AFTER INSERT OR UPDATE OR DELETE ON agent_runtime_invocations
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION agent_check_run_invocation_aggregate();
"""


REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS agent_invocation_aggregate_check ON agent_runtime_invocations;
DROP TRIGGER IF EXISTS agent_run_invocation_aggregate_check ON agent_run_attempts;
DROP TRIGGER IF EXISTS agent_invocation_progress_guard ON agent_runtime_invocations;
DROP TRIGGER IF EXISTS agent_invocation_append_guard ON agent_runtime_invocations;
DROP TRIGGER IF EXISTS agent_terminal_command_fingerprint_guard ON agent_run_terminal_events;
DROP TRIGGER IF EXISTS agent_outcome_command_fingerprint_guard ON agent_outcome_submissions;
DROP TRIGGER IF EXISTS agent_invocation_command_fingerprint_guard ON agent_runtime_invocations;
DROP TRIGGER IF EXISTS agent_input_command_fingerprint_guard ON agent_run_input_events;
DROP TRIGGER IF EXISTS agent_run_command_fingerprint_guard ON agent_run_attempts;
DROP TRIGGER IF EXISTS agent_assignment_commission_guard ON agent_assignment_contracts;
DROP TRIGGER IF EXISTS agent_run_assignment_lock ON agent_run_attempts;
DROP FUNCTION IF EXISTS agent_check_run_invocation_aggregate();
DROP FUNCTION IF EXISTS agent_lock_assignment_for_run();
DROP FUNCTION IF EXISTS agent_guard_invocation_progress();
DROP FUNCTION IF EXISTS agent_guard_invocation_append_only();
DROP FUNCTION IF EXISTS agent_guard_command_fingerprint_immutable();
DROP FUNCTION IF EXISTS agent_guard_assignment_commission_immutable();
"""


class Migration(migrations.Migration):
    dependencies = [("db", "0124_agent_lifecycle_database_integrity")]

    operations = [
        migrations.AddField(
            model_name="runattempt",
            name="command_fingerprint",
            field=models.CharField(blank=True, editable=False, max_length=72, null=True),
        ),
        migrations.AddField(
            model_name="runinputevent",
            name="command_fingerprint",
            field=models.CharField(blank=True, editable=False, max_length=72, null=True),
        ),
        migrations.AddField(
            model_name="runtimeinvocation",
            name="command_fingerprint",
            field=models.CharField(blank=True, editable=False, max_length=72, null=True),
        ),
        migrations.AddField(
            model_name="runtimeinvocation",
            name="ordinal",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="runtimeinvocation",
            name="usage",
            field=models.JSONField(default=plane.db.models.agent.default_dict),
        ),
        migrations.AddField(
            model_name="outcomesubmission",
            name="command_fingerprint",
            field=models.CharField(blank=True, editable=False, max_length=72, null=True),
        ),
        migrations.AddField(
            model_name="runterminalevent",
            name="command_fingerprint",
            field=models.CharField(blank=True, editable=False, max_length=72, null=True),
        ),
        migrations.RunSQL(BACKFILL_SQL, migrations.RunSQL.noop),
        migrations.AddConstraint(
            model_name="runtimeinvocation",
            constraint=models.UniqueConstraint(fields=("run", "ordinal"), name="agent_invocation_run_ordinal_unique"),
        ),
        migrations.AddConstraint(
            model_name="runtimeinvocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("ordinal__gte", 1)), name="agent_invocation_ordinal_positive"
            ),
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
