# Generated by Django 5.2.15 on 2026-08-05

import hashlib
import json

import plane.db.models.agent
from django.db import migrations, models


BACKFILL_SQL = r"""
WITH ranked AS (
    SELECT id, row_number() OVER (PARTITION BY run_id ORDER BY created_at, id) AS ordinal
    FROM agent_runtime_invocations
)
UPDATE agent_runtime_invocations AS i
SET ordinal = ranked.ordinal
FROM ranked
WHERE i.id = ranked.id;
"""


_LEGACY_FINGERPRINT_PREFIX = "legacy1:"
_COUNTERS = ("inputTokens", "outputTokens", "durationMs")


def _canonical_json(value):
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False)


def _legacy_fingerprint(operation, binding):
    command = _canonical_json({"version": "agent-lifecycle-0125-legacy-v1", "operation": operation, "binding": binding})
    return f"{_LEGACY_FINGERPRINT_PREFIX}{hashlib.sha256(command.encode('utf-8')).hexdigest()}"


def _identifier(value):
    return str(value) if value is not None else None


def _full_usage(value):
    if not isinstance(value, dict) or set(value) != set(_COUNTERS):
        return None
    result = {}
    for field in _COUNTERS:
        amount = value[field]
        if not isinstance(amount, int) or isinstance(amount, bool) or amount < 0:
            return None
        result[field] = amount
    return result


def _all_rows(model):
    """Use the unfiltered historical manager when Django rebuilds model state."""

    return getattr(model, "all_objects", model._base_manager)


def _reconstruct_invocation_usage(run, invocations):
    """Recover legacy per-invocation deltas from the persisted budget observations."""

    total = _full_usage(run.snapshot.get("totalBudget"))
    final = _full_usage(run.cumulative_usage)
    if total is None or final is None:
        return None
    before = {field: 0 for field in _COUNTERS}
    reconstructed = {}
    for index, invocation in enumerate(invocations):
        remaining = invocation.envelope.get("remainingBudget")
        remaining = _full_usage(remaining)
        if remaining is None:
            return None
        observed_before = {field: total[field] - remaining[field] for field in _COUNTERS}
        if any(value < 0 for value in observed_before.values()) or observed_before != before:
            return None
        if index + 1 < len(invocations):
            next_remaining = invocations[index + 1].envelope.get("remainingBudget")
            next_remaining = _full_usage(next_remaining)
            if next_remaining is None:
                return None
            after = {field: total[field] - next_remaining[field] for field in _COUNTERS}
        else:
            after = final
        delta = {field: after[field] - before[field] for field in _COUNTERS}
        if any(value < 0 for value in delta.values()):
            return None
        reconstructed[invocation.id] = delta
        before = after
    if before != final:
        return None
    return reconstructed


def _backfill_legacy_bindings(apps, schema_editor):
    RunAttempt = apps.get_model("db", "RunAttempt")
    RunInputEvent = apps.get_model("db", "RunInputEvent")
    RuntimeInvocation = apps.get_model("db", "RuntimeInvocation")
    OutcomeSubmission = apps.get_model("db", "OutcomeSubmission")
    RunTerminalEvent = apps.get_model("db", "RunTerminalEvent")

    runs = list(_all_rows(RunAttempt).all())
    for run in runs:
        invocations = list(_all_rows(RuntimeInvocation).filter(run_id=run.id).order_by("ordinal", "id"))
        usage_by_id = _reconstruct_invocation_usage(run, invocations)
        if usage_by_id is not None:
            for invocation in invocations:
                _all_rows(RuntimeInvocation).filter(pk=invocation.pk).update(usage=usage_by_id[invocation.id])

    for row in _all_rows(RunAttempt).filter(creation_idempotency_key__isnull=False).iterator():
        _all_rows(RunAttempt).filter(pk=row.pk).update(
            command_fingerprint=_legacy_fingerprint(
                "create_run",
                {
                    "assignmentId": _identifier(row.assignment_id),
                    "profileVersionId": _identifier(row.profile_version_id),
                    "snapshot": row.snapshot,
                    "lineageOf": _identifier(row.lineage_of_id),
                    "lineageReason": row.lineage_reason,
                    "recoveryOf": _identifier(row.recovery_of_id),
                    "recoveryIntent": row.recovery_intent,
                    "createdBy": _identifier(row.created_by_id),
                },
            )
        )

    for row in _all_rows(RunInputEvent).filter(idempotency_key__isnull=False).iterator():
        _all_rows(RunInputEvent).filter(pk=row.pk).update(
            command_fingerprint=_legacy_fingerprint(
                "record_input_event",
                {
                    "runId": _identifier(row.run_id),
                    "kind": row.kind,
                    "payload": row.payload,
                    "pendingInputRef": row.pending_input_ref,
                    "createdBy": _identifier(row.created_by_id),
                },
            )
        )

    for row in _all_rows(RuntimeInvocation).filter(idempotency_key__isnull=False).iterator():
        context_refs = row.envelope.get("newContextEventRefs") or []
        _all_rows(RuntimeInvocation).filter(pk=row.pk).update(
            command_fingerprint=_legacy_fingerprint(
                "record_invocation",
                {
                    "runId": _identifier(row.run_id),
                    "invocationId": row.invocation_id,
                    "trigger": row.envelope.get("trigger"),
                    "inputEventRef": context_refs[0] if context_refs else None,
                    "usage": _full_usage(row.usage),
                    "createdBy": _identifier(row.created_by_id),
                },
            )
        )

    for row in _all_rows(OutcomeSubmission).filter(submission_idempotency_key__isnull=False).iterator():
        _all_rows(OutcomeSubmission).filter(pk=row.pk).update(
            command_fingerprint=_legacy_fingerprint(
                "propose_outcome",
                {
                    "runId": _identifier(row.run_id),
                    "summary": row.summary,
                    "artifacts": row.artifacts,
                    "evidence": row.evidence,
                    "createdBy": _identifier(row.created_by_id),
                },
            )
        )

    for row in _all_rows(RunTerminalEvent).filter(idempotency_key__isnull=False).iterator():
        _all_rows(RunTerminalEvent).filter(pk=row.pk).update(
            command_fingerprint=_legacy_fingerprint(
                "record_terminal_event",
                {
                    "invocationId": _identifier(row.invocation_id),
                    "runId": _identifier(row.run_id),
                    "kind": row.kind,
                    "source": row.source,
                    "productRef": row.product_ref,
                    "productEventRef": row.product_event_ref,
                    "idempotencyKey": row.idempotency_key,
                    "reason": row.reason,
                    "cancellationRef": row.cancellation_ref,
                },
            )
        )


DROP_BACKFILL_TRIGGERS_SQL = """
DROP TRIGGER IF EXISTS agent_run_terminal_check ON agent_run_attempts;
DROP TRIGGER IF EXISTS agent_invocation_terminal_check ON agent_runtime_invocations;
DROP TRIGGER IF EXISTS agent_outcome_terminal_check ON agent_outcome_submissions;
DROP TRIGGER IF EXISTS agent_terminal_append_guard ON agent_run_terminal_events;
"""

CREATE_BACKFILL_TRIGGERS_SQL = """
CREATE CONSTRAINT TRIGGER agent_run_terminal_check
AFTER INSERT OR UPDATE ON agent_run_attempts DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION agent_check_run_terminal();
CREATE CONSTRAINT TRIGGER agent_invocation_terminal_check
AFTER INSERT OR UPDATE ON agent_runtime_invocations DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION agent_check_invocation_terminal();
CREATE CONSTRAINT TRIGGER agent_outcome_terminal_check
AFTER INSERT OR UPDATE ON agent_outcome_submissions DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION agent_check_outcome_terminal();
CREATE TRIGGER agent_terminal_append_guard
BEFORE UPDATE OR DELETE ON agent_run_terminal_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_terminal_append_only();
"""


FORWARD_SQL = r"""
CREATE OR REPLACE FUNCTION agent_guard_assignment_commission_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        PERFORM 1 FROM agent_assignment_contracts WHERE id = OLD.id FOR UPDATE;
        IF EXISTS (SELECT 1 FROM agent_run_attempts WHERE assignment_id = OLD.id)
           AND (
               NEW.workspace_id IS DISTINCT FROM OLD.workspace_id
               OR NEW.project_id IS DISTINCT FROM OLD.project_id
               OR NEW.assignee_id IS DISTINCT FROM OLD.assignee_id
               OR NEW.lineage_of_id IS DISTINCT FROM OLD.lineage_of_id
               OR NEW.target_ref IS DISTINCT FROM OLD.target_ref
               OR NEW.objective IS DISTINCT FROM OLD.objective
               OR NEW.acceptance_criteria IS DISTINCT FROM OLD.acceptance_criteria
               OR NEW.context_refs IS DISTINCT FROM OLD.context_refs
           ) THEN
            RAISE EXCEPTION 'Assignment commission is immutable after execution begins'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_lock_assignment_for_run() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    PERFORM 1 FROM agent_assignment_contracts WHERE id = NEW.assignment_id FOR KEY SHARE;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_command_fingerprint_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.command_fingerprint IS DISTINCT FROM OLD.command_fingerprint THEN
        IF OLD.command_fingerprint ~ '^legacy1:[0-9a-f]{64}$'
           AND NEW.command_fingerprint ~ '^command:[0-9a-f]{64}$' THEN
            RETURN NEW;
        END IF;
        RAISE EXCEPTION 'Idempotent command fingerprints are immutable' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_keyed_record_delete() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Idempotency-bound Agent records cannot be deleted' USING ERRCODE = 'check_violation';
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_keyed_record_binding_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    is_keyed boolean;
    excluded_columns text[];
BEGIN
    EXECUTE format('SELECT ($1).%I IS NOT NULL', TG_ARGV[0])
    INTO is_keyed
    USING OLD;
    IF NOT is_keyed THEN
        RETURN NEW;
    END IF;
    excluded_columns := string_to_array(TG_ARGV[1], ',');
    IF (to_jsonb(NEW) - excluded_columns) IS DISTINCT FROM (to_jsonb(OLD) - excluded_columns) THEN
        RAISE EXCEPTION 'Idempotency-bound Agent record fields are immutable'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_invocation_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'RuntimeInvocation is append-only' USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.ordinal IS DISTINCT FROM OLD.ordinal OR NEW.usage IS DISTINCT FROM OLD.usage THEN
        RAISE EXCEPTION 'RuntimeInvocation ordinal and usage are immutable' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_invocation_progress() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    current_count integer;
    usage_field text;
BEGIN
    SELECT invocation_count INTO current_count
    FROM agent_run_attempts
    WHERE id = NEW.run_id
    FOR UPDATE;
    IF current_count IS NULL OR NEW.ordinal <> current_count + 1 THEN
        RAISE EXCEPTION 'RuntimeInvocation ordinal must be the next run ordinal'
            USING ERRCODE = 'check_violation';
    END IF;
    IF jsonb_typeof(NEW.usage) IS DISTINCT FROM 'object'
       OR NOT (NEW.usage ?& ARRAY['inputTokens', 'outputTokens', 'durationMs'])
       OR (SELECT count(*) FROM jsonb_object_keys(NEW.usage)) <> 3 THEN
        RAISE EXCEPTION 'RuntimeInvocation usage must contain exactly the accepted counters'
            USING ERRCODE = 'check_violation';
    END IF;
    FOREACH usage_field IN ARRAY ARRAY['inputTokens', 'outputTokens', 'durationMs'] LOOP
        IF jsonb_typeof(NEW.usage -> usage_field) <> 'number'
           OR (NEW.usage ->> usage_field)::numeric < 0
           OR (NEW.usage ->> usage_field)::numeric > 2147483647
           OR (NEW.usage ->> usage_field)::numeric <> trunc((NEW.usage ->> usage_field)::numeric) THEN
            RAISE EXCEPTION 'RuntimeInvocation usage counters must be bounded non-negative integers'
                USING ERRCODE = 'check_violation';
        END IF;
    END LOOP;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_guard_terminal_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'UPDATE'
       AND OLD.command_fingerprint ~ '^legacy1:[0-9a-f]{64}$'
       AND NEW.command_fingerprint ~ '^command:[0-9a-f]{64}$'
    THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'RunTerminalEvent is append-only' USING ERRCODE = 'check_violation';
END;
$$;

CREATE OR REPLACE FUNCTION agent_check_run_invocation_aggregate() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    checked_run uuid;
    expected_count integer;
    expected_last text;
    expected_usage jsonb;
    actual_count integer;
    actual_usage jsonb;
BEGIN
    IF TG_TABLE_NAME = 'agent_runtime_invocations' THEN
        IF TG_OP = 'DELETE' THEN
            checked_run := OLD.run_id;
        ELSE
            checked_run := NEW.run_id;
        END IF;
    ELSE
        checked_run := NEW.id;
    END IF;
    SELECT invocation_count, last_invocation_id, cumulative_usage
    INTO expected_count, expected_last, expected_usage
    FROM agent_run_attempts
    WHERE id = checked_run;
    SELECT count(*)::integer,
           jsonb_build_object(
               'inputTokens', COALESCE(sum((usage ->> 'inputTokens')::bigint), 0),
               'outputTokens', COALESCE(sum((usage ->> 'outputTokens')::bigint), 0),
               'durationMs', COALESCE(sum((usage ->> 'durationMs')::bigint), 0)
           )
    INTO actual_count, actual_usage
    FROM agent_runtime_invocations
    WHERE run_id = checked_run;
    IF expected_count IS NULL
       OR expected_count <> actual_count
       OR expected_usage IS DISTINCT FROM actual_usage
       OR (expected_count = 0 AND expected_last IS NOT NULL)
       OR (expected_count > 0 AND NOT EXISTS (
           SELECT 1 FROM agent_runtime_invocations
           WHERE run_id = checked_run AND ordinal = expected_count
             AND invocation_id = expected_last
       )) THEN
        RAISE EXCEPTION 'Run invocation count and cumulative usage must equal the invocation aggregate'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END;
$$;

CREATE TRIGGER agent_assignment_commission_guard
BEFORE UPDATE ON agent_assignment_contracts
FOR EACH ROW EXECUTE FUNCTION agent_guard_assignment_commission_immutable();
CREATE TRIGGER agent_run_assignment_lock
BEFORE INSERT ON agent_run_attempts
FOR EACH ROW EXECUTE FUNCTION agent_lock_assignment_for_run();

CREATE TRIGGER agent_run_command_fingerprint_guard
BEFORE UPDATE ON agent_run_attempts
FOR EACH ROW EXECUTE FUNCTION agent_guard_command_fingerprint_immutable();
CREATE TRIGGER agent_input_command_fingerprint_guard
BEFORE UPDATE ON agent_run_input_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_command_fingerprint_immutable();
CREATE TRIGGER agent_invocation_command_fingerprint_guard
BEFORE UPDATE ON agent_runtime_invocations
FOR EACH ROW EXECUTE FUNCTION agent_guard_command_fingerprint_immutable();
CREATE TRIGGER agent_outcome_command_fingerprint_guard
BEFORE UPDATE ON agent_outcome_submissions
FOR EACH ROW EXECUTE FUNCTION agent_guard_command_fingerprint_immutable();
CREATE TRIGGER agent_terminal_command_fingerprint_guard
BEFORE UPDATE ON agent_run_terminal_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_command_fingerprint_immutable();

CREATE TRIGGER agent_run_keyed_delete_guard
BEFORE DELETE ON agent_run_attempts
FOR EACH ROW WHEN (OLD.creation_idempotency_key IS NOT NULL)
EXECUTE FUNCTION agent_guard_keyed_record_delete();
CREATE TRIGGER agent_input_keyed_delete_guard
BEFORE DELETE ON agent_run_input_events
FOR EACH ROW WHEN (OLD.idempotency_key IS NOT NULL)
EXECUTE FUNCTION agent_guard_keyed_record_delete();
CREATE TRIGGER agent_invocation_keyed_delete_guard
BEFORE DELETE ON agent_runtime_invocations
FOR EACH ROW WHEN (OLD.idempotency_key IS NOT NULL)
EXECUTE FUNCTION agent_guard_keyed_record_delete();
CREATE TRIGGER agent_outcome_keyed_delete_guard
BEFORE DELETE ON agent_outcome_submissions
FOR EACH ROW WHEN (OLD.submission_idempotency_key IS NOT NULL)
EXECUTE FUNCTION agent_guard_keyed_record_delete();
CREATE TRIGGER agent_terminal_keyed_delete_guard
BEFORE DELETE ON agent_run_terminal_events
FOR EACH ROW WHEN (OLD.idempotency_key IS NOT NULL)
EXECUTE FUNCTION agent_guard_keyed_record_delete();

CREATE TRIGGER agent_run_keyed_binding_guard
BEFORE UPDATE ON agent_run_attempts
FOR EACH ROW EXECUTE FUNCTION agent_guard_keyed_record_binding_immutable(
    'creation_idempotency_key',
    'command_fingerprint,deleted_at,updated_at,updated_by_id,state,invocation_count,last_invocation_id,cumulative_usage'
);
CREATE TRIGGER agent_input_keyed_binding_guard
BEFORE UPDATE ON agent_run_input_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_keyed_record_binding_immutable(
    'idempotency_key', 'command_fingerprint,deleted_at,updated_at,updated_by_id'
);
CREATE TRIGGER agent_invocation_keyed_binding_guard
BEFORE UPDATE ON agent_runtime_invocations
FOR EACH ROW EXECUTE FUNCTION agent_guard_keyed_record_binding_immutable(
    'idempotency_key', 'command_fingerprint,deleted_at,updated_at,updated_by_id,state'
);
CREATE TRIGGER agent_outcome_keyed_binding_guard
BEFORE UPDATE ON agent_outcome_submissions
FOR EACH ROW EXECUTE FUNCTION agent_guard_keyed_record_binding_immutable(
    'submission_idempotency_key',
    'command_fingerprint,deleted_at,updated_at,updated_by_id,state,evaluator_id,evaluator_feedback,'
    'evaluator_reviewed_at,human_reviewer_id,human_decision_note,human_decided_at'
);
CREATE TRIGGER agent_terminal_keyed_binding_guard
BEFORE UPDATE ON agent_run_terminal_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_keyed_record_binding_immutable(
    'idempotency_key', 'command_fingerprint,deleted_at,updated_at,updated_by_id'
);

CREATE TRIGGER agent_invocation_append_guard
BEFORE UPDATE OR DELETE ON agent_runtime_invocations
FOR EACH ROW EXECUTE FUNCTION agent_guard_invocation_append_only();
CREATE TRIGGER agent_invocation_progress_guard
BEFORE INSERT ON agent_runtime_invocations
FOR EACH ROW EXECUTE FUNCTION agent_guard_invocation_progress();

CREATE CONSTRAINT TRIGGER agent_run_invocation_aggregate_check
AFTER INSERT OR UPDATE OF invocation_count, last_invocation_id, cumulative_usage ON agent_run_attempts
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION agent_check_run_invocation_aggregate();
CREATE CONSTRAINT TRIGGER agent_invocation_aggregate_check
AFTER INSERT OR UPDATE OR DELETE ON agent_runtime_invocations
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION agent_check_run_invocation_aggregate();
"""


REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS agent_invocation_aggregate_check ON agent_runtime_invocations;
DROP TRIGGER IF EXISTS agent_run_invocation_aggregate_check ON agent_run_attempts;
DROP TRIGGER IF EXISTS agent_invocation_progress_guard ON agent_runtime_invocations;
DROP TRIGGER IF EXISTS agent_invocation_append_guard ON agent_runtime_invocations;
DROP TRIGGER IF EXISTS agent_terminal_command_fingerprint_guard ON agent_run_terminal_events;
DROP TRIGGER IF EXISTS agent_outcome_command_fingerprint_guard ON agent_outcome_submissions;
DROP TRIGGER IF EXISTS agent_invocation_command_fingerprint_guard ON agent_runtime_invocations;
DROP TRIGGER IF EXISTS agent_input_command_fingerprint_guard ON agent_run_input_events;
DROP TRIGGER IF EXISTS agent_run_command_fingerprint_guard ON agent_run_attempts;
DROP TRIGGER IF EXISTS agent_terminal_keyed_delete_guard ON agent_run_terminal_events;
DROP TRIGGER IF EXISTS agent_outcome_keyed_delete_guard ON agent_outcome_submissions;
DROP TRIGGER IF EXISTS agent_invocation_keyed_delete_guard ON agent_runtime_invocations;
DROP TRIGGER IF EXISTS agent_input_keyed_delete_guard ON agent_run_input_events;
DROP TRIGGER IF EXISTS agent_run_keyed_delete_guard ON agent_run_attempts;
DROP TRIGGER IF EXISTS agent_terminal_keyed_binding_guard ON agent_run_terminal_events;
DROP TRIGGER IF EXISTS agent_outcome_keyed_binding_guard ON agent_outcome_submissions;
DROP TRIGGER IF EXISTS agent_invocation_keyed_binding_guard ON agent_runtime_invocations;
DROP TRIGGER IF EXISTS agent_input_keyed_binding_guard ON agent_run_input_events;
DROP TRIGGER IF EXISTS agent_run_keyed_binding_guard ON agent_run_attempts;
DROP TRIGGER IF EXISTS agent_assignment_commission_guard ON agent_assignment_contracts;
DROP TRIGGER IF EXISTS agent_run_assignment_lock ON agent_run_attempts;
DROP FUNCTION IF EXISTS agent_check_run_invocation_aggregate();
DROP FUNCTION IF EXISTS agent_lock_assignment_for_run();
DROP FUNCTION IF EXISTS agent_guard_invocation_progress();
DROP FUNCTION IF EXISTS agent_guard_invocation_append_only();
DROP FUNCTION IF EXISTS agent_guard_command_fingerprint_immutable();
DROP FUNCTION IF EXISTS agent_guard_keyed_record_binding_immutable();
DROP FUNCTION IF EXISTS agent_guard_keyed_record_delete();
DROP FUNCTION IF EXISTS agent_guard_assignment_commission_immutable();
CREATE OR REPLACE FUNCTION agent_guard_terminal_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'RunTerminalEvent is append-only' USING ERRCODE = 'check_violation';
END;
$$;
"""


class Migration(migrations.Migration):
    dependencies = [("db", "0124_agent_lifecycle_database_integrity")]

    operations = [
        migrations.RunSQL(DROP_BACKFILL_TRIGGERS_SQL, CREATE_BACKFILL_TRIGGERS_SQL),
        migrations.AddField(
            model_name="runattempt",
            name="command_fingerprint",
            field=models.CharField(blank=True, editable=False, max_length=72, null=True),
        ),
        migrations.AddField(
            model_name="runinputevent",
            name="command_fingerprint",
            field=models.CharField(blank=True, editable=False, max_length=72, null=True),
        ),
        migrations.AddField(
            model_name="runtimeinvocation",
            name="command_fingerprint",
            field=models.CharField(blank=True, editable=False, max_length=72, null=True),
        ),
        migrations.AddField(
            model_name="runtimeinvocation",
            name="ordinal",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="runtimeinvocation",
            name="usage",
            field=models.JSONField(default=plane.db.models.agent.default_dict),
        ),
        migrations.AddField(
            model_name="outcomesubmission",
            name="command_fingerprint",
            field=models.CharField(blank=True, editable=False, max_length=72, null=True),
        ),
        migrations.AddField(
            model_name="runterminalevent",
            name="command_fingerprint",
            field=models.CharField(blank=True, editable=False, max_length=72, null=True),
        ),
        migrations.RunSQL(BACKFILL_SQL, migrations.RunSQL.noop),
        migrations.RunPython(_backfill_legacy_bindings, migrations.RunPython.noop),
        migrations.RunSQL(
            "SET CONSTRAINTS ALL IMMEDIATE; SET CONSTRAINTS ALL DEFERRED;",
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(CREATE_BACKFILL_TRIGGERS_SQL, DROP_BACKFILL_TRIGGERS_SQL),
        migrations.AddConstraint(
            model_name="runattempt",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(creation_idempotency_key__isnull=True, command_fingerprint__isnull=True)
                    | models.Q(
                        creation_idempotency_key__isnull=False,
                        command_fingerprint__isnull=False,
                        command_fingerprint__regex=r"^(command|legacy[12]):[0-9a-f]{64}$",
                    )
                ),
                name="agent_run_command_fingerprint_binding",
            ),
        ),
        migrations.AddConstraint(
            model_name="runinputevent",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(idempotency_key__isnull=True, command_fingerprint__isnull=True)
                    | models.Q(
                        idempotency_key__isnull=False,
                        command_fingerprint__isnull=False,
                        command_fingerprint__regex=r"^(command|legacy[12]):[0-9a-f]{64}$",
                    )
                ),
                name="agent_input_command_fingerprint_binding",
            ),
        ),
        migrations.AddConstraint(
            model_name="runtimeinvocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    command_fingerprint__isnull=False,
                    command_fingerprint__regex=r"^(command|legacy[12]):[0-9a-f]{64}$",
                ),
                name="agent_invocation_command_fingerprint_binding",
            ),
        ),
        migrations.AddConstraint(
            model_name="outcomesubmission",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(submission_idempotency_key__isnull=True, command_fingerprint__isnull=True)
                    | models.Q(
                        submission_idempotency_key__isnull=False,
                        command_fingerprint__isnull=False,
                        command_fingerprint__regex=r"^(command|legacy[12]):[0-9a-f]{64}$",
                    )
                ),
                name="agent_outcome_command_fingerprint_binding",
            ),
        ),
        migrations.AddConstraint(
            model_name="runterminalevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    command_fingerprint__isnull=False,
                    command_fingerprint__regex=r"^(command|legacy[12]):[0-9a-f]{64}$",
                ),
                name="agent_terminal_command_fingerprint_binding",
            ),
        ),
        migrations.AddConstraint(
            model_name="runtimeinvocation",
            constraint=models.UniqueConstraint(fields=("run", "ordinal"), name="agent_invocation_run_ordinal_unique"),
        ),
        migrations.AddConstraint(
            model_name="runtimeinvocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("ordinal__gte", 1)), name="agent_invocation_ordinal_positive"
            ),
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
