# Generated by Django 5.2.15 on 2026-08-04 00:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0125_agent_lifecycle_append_only_integrity"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationGatewayAudit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("phase", models.CharField(choices=[("intent", "Intent"), ("outcome", "Outcome")], max_length=16)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("intent", "Intent"),
                            ("success", "Success"),
                            ("denied", "Denied"),
                            ("failure", "Failure"),
                            ("outcome_unknown", "Outcome unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                ("request_id", models.UUIDField()),
                ("operation_id", models.CharField(max_length=128)),
                ("workspace_slug", models.CharField(max_length=255)),
                ("caller_id", models.UUIDField()),
                ("idempotency_key", models.CharField(max_length=128)),
                ("correlation_id", models.CharField(max_length=128)),
                ("request_digest", models.CharField(max_length=64)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "operation_gateway_audit",
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="OperationGatewayIdempotency",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("request_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("operation_id", models.CharField(max_length=128)),
                ("workspace_slug", models.CharField(max_length=255)),
                ("caller_id", models.UUIDField()),
                ("idempotency_key", models.CharField(max_length=128)),
                ("correlation_id", models.CharField(max_length=128)),
                ("request_digest", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("denied", "Denied"),
                            ("failed_precommit", "Failed before commit"),
                            ("outcome_unknown", "Outcome unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.JSONField(blank=True, null=True)),
                ("audit_receipt", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "operation_gateway_idempotency"},
        ),
        migrations.AddConstraint(
            model_name="operationgatewayidempotency",
            constraint=models.UniqueConstraint(
                fields=("workspace_slug", "caller_id", "idempotency_key"),
                name="operation_gateway_idempotency_key",
            ),
        ),
        migrations.AddIndex(
            model_name="operationgatewayidempotency",
            index=models.Index(fields=("caller_id", "created_at"), name="op_gateway_caller_created"),
        ),
        migrations.AddIndex(
            model_name="operationgatewayaudit",
            index=models.Index(fields=("workspace_slug", "created_at"), name="op_gateway_audit_workspace"),
        ),
        migrations.AddIndex(
            model_name="operationgatewayaudit",
            index=models.Index(fields=("caller_id", "created_at"), name="op_gateway_audit_caller"),
        ),
    ]
