# Generated by Django 5.2.15 on 2026-08-04

"""Finish the gateway receipt schema without callable-default backfills.

Historical rows are grouped by their legacy request_id.  A matching
idempotency row and all of its audit rows share one deterministic invocation
UUID.  Unmatched or ambiguous audit rows receive a deterministic UUID derived
from their own primary key, so they cannot collide or be silently linked to a
different request.  This rule is deliberately data-local and rerunnable.
"""

import uuid

from django.db import migrations, models


INVOCATION_NAMESPACE = uuid.UUID("6bcb4d91-fb3e-5d76-93c4-8fcebd9b6d3f")


def _stable_invocation(prefix: str, value: object) -> uuid.UUID:
    return uuid.uuid5(INVOCATION_NAMESPACE, f"{prefix}:{value}")


def backfill_gateway_history(apps, schema_editor):
    Workspace = apps.get_model("db", "Workspace")
    Audit = apps.get_model("db", "OperationGatewayAudit")
    Idempotency = apps.get_model("db", "OperationGatewayIdempotency")
    workspace_ids = dict(Workspace.objects.values_list("slug", "id"))

    idempotency_by_request = {}
    for record in Idempotency.objects.order_by("created_at", "id"):
        if record.workspace_id is None:
            workspace_id = workspace_ids.get(record.workspace_slug)
            if workspace_id is not None:
                record.workspace_id = workspace_id
        record.invocation_id = _stable_invocation("idempotency", record.pk)
        record.save(update_fields=["workspace_id", "invocation_id"])
        idempotency_by_request.setdefault(record.request_id, []).append(record)

    for record in Audit.objects.order_by("created_at", "id"):
        matches = [
            candidate
            for candidate in idempotency_by_request.get(record.request_id, [])
            if candidate.operation_id == record.operation_id
            and candidate.workspace_slug == record.workspace_slug
            and candidate.caller_id == record.caller_id
            and candidate.idempotency_key == record.idempotency_key
            and candidate.correlation_id == record.correlation_id
            and candidate.request_digest == record.request_digest
        ]
        if len(matches) == 1:
            record.invocation_id = matches[0].invocation_id
        else:
            # No safe linkage exists. Keep the row auditable without inventing
            # a relationship; the primary key makes the UUID collision-free.
            record.invocation_id = _stable_invocation("audit", record.pk)
        if record.workspace_id is None:
            workspace_id = workspace_ids.get(record.workspace_slug)
            if workspace_id is not None:
                record.workspace_id = workspace_id
        record.save(update_fields=["invocation_id", "workspace_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0126_operationgatewayaudit_operationgatewayidempotency"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationgatewayaudit",
            name="invocation_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="operationgatewayaudit",
            name="workspace_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="operationgatewayidempotency",
            name="invocation_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="operationgatewayidempotency",
            name="request_input",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="operationgatewayidempotency",
            name="retryable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="operationgatewayidempotency",
            name="workspace_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(backfill_gateway_history, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="operationgatewayidempotency",
            name="operation_gateway_idempotency_key",
        ),
        migrations.AddConstraint(
            model_name="operationgatewayidempotency",
            constraint=models.UniqueConstraint(
                fields=("workspace_id", "caller_id", "operation_id", "idempotency_key"),
                name="operation_gateway_idempotency_key",
            ),
        ),
        migrations.AddIndex(
            model_name="operationgatewayidempotency",
            index=models.Index(fields=("workspace_id", "created_at"), name="op_gateway_workspace_created"),
        ),
        migrations.AddIndex(
            model_name="operationgatewayaudit",
            index=models.Index(fields=("workspace_id", "created_at"), name="op_gateway_audit_workspace_id"),
        ),
        migrations.AlterField(
            model_name="operationgatewayidempotency",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("denied", "Denied"),
                    ("failed_precommit", "Failed before commit"),
                    ("outcome_unknown", "Outcome unknown"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="operationgatewayaudit",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("intent", "Intent"),
                    ("success", "Success"),
                    ("denied", "Denied"),
                    ("failure", "Failure"),
                    ("outcome_unknown", "Outcome unknown"),
                    ("replay", "Replay"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="operationgatewayaudit",
            name="invocation_id",
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name="operationgatewayidempotency",
            name="invocation_id",
            field=models.UUIDField(editable=False),
        ),
    ]
