# Generated by Django 5.2.15 on 2026-08-05

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


CREATE_RUNTIME_EVIDENCE_GUARDS = """
CREATE OR REPLACE FUNCTION agent_runtime_event_ingress_append_only()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'runtime event ingress records are append-only'
        USING ERRCODE = '55000';
END;
$$;

CREATE OR REPLACE FUNCTION agent_runtime_exit_evidence_append_only()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'runtime exit evidence records are append-only'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER agent_runtime_event_ingress_append_only
BEFORE UPDATE OR DELETE ON agent_runtime_event_ingress
FOR EACH ROW
EXECUTE FUNCTION agent_runtime_event_ingress_append_only();

CREATE TRIGGER agent_runtime_event_ingress_append_only_truncate
BEFORE TRUNCATE ON agent_runtime_event_ingress
FOR EACH STATEMENT
EXECUTE FUNCTION agent_runtime_event_ingress_append_only();

CREATE TRIGGER agent_runtime_exit_evidence_append_only
BEFORE UPDATE OR DELETE ON agent_runtime_exit_evidence
FOR EACH ROW
EXECUTE FUNCTION agent_runtime_exit_evidence_append_only();

CREATE TRIGGER agent_runtime_exit_evidence_append_only_truncate
BEFORE TRUNCATE ON agent_runtime_exit_evidence
FOR EACH STATEMENT
EXECUTE FUNCTION agent_runtime_exit_evidence_append_only();
"""

DROP_RUNTIME_EVIDENCE_GUARDS = """
DROP TRIGGER IF EXISTS agent_runtime_event_ingress_append_only ON agent_runtime_event_ingress;
DROP TRIGGER IF EXISTS agent_runtime_event_ingress_append_only_truncate ON agent_runtime_event_ingress;
DROP TRIGGER IF EXISTS agent_runtime_exit_evidence_append_only ON agent_runtime_exit_evidence;
DROP TRIGGER IF EXISTS agent_runtime_exit_evidence_append_only_truncate ON agent_runtime_exit_evidence;
DROP FUNCTION IF EXISTS agent_runtime_event_ingress_append_only();
DROP FUNCTION IF EXISTS agent_runtime_exit_evidence_append_only();
"""


class Migration(migrations.Migration):
    dependencies = [("db", "0129_operationgateway_delivery_and_audit_roles")]

    operations = [
        migrations.CreateModel(
            name="RuntimeEventIngress",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("snapshot_content_digest", models.CharField(editable=False, max_length=73)),
                ("event_id", models.CharField(editable=False, max_length=128, unique=True)),
                ("idempotency_key", models.CharField(editable=False, max_length=128, unique=True)),
                ("correlation_id", models.CharField(editable=False, max_length=128)),
                ("causation_ref", models.CharField(editable=False, max_length=128)),
                ("sequence", models.PositiveIntegerField(editable=False)),
                ("fingerprint", models.CharField(editable=False, max_length=72)),
                ("kind", models.CharField(editable=False, max_length=64)),
                ("observed_at", models.CharField(editable=False, max_length=64)),
                ("raw_payload", models.JSONField(editable=False)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_event_ingress",
                        to="db.agentactor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "invocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_events",
                        to="db.runtimeinvocation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_event_ingress",
                        to="db.runattempt",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "agent_runtime_event_ingress",
                "ordering": ("invocation_id", "sequence"),
                "indexes": [
                    models.Index(fields=("invocation", "sequence"), name="agent_rt_event_seq"),
                    models.Index(fields=("run", "created_at"), name="agent_rt_event_run"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("invocation", "sequence"), name="agent_rt_event_inv_seq"),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 0)), name="agent_rt_event_seq_nonnegative"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RuntimeExitEvidence",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("snapshot_content_digest", models.CharField(editable=False, max_length=73)),
                ("idempotency_key", models.CharField(editable=False, max_length=128, unique=True)),
                ("correlation_id", models.CharField(editable=False, max_length=128)),
                ("causation_ref", models.CharField(editable=False, max_length=128)),
                ("final_sequence", models.PositiveIntegerField(editable=False)),
                ("fingerprint", models.CharField(editable=False, max_length=72)),
                ("kind", models.CharField(editable=False, max_length=32)),
                ("raw_payload", models.JSONField(editable=False)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_exit_evidence",
                        to="db.agentactor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "invocation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_exit",
                        to="db.runtimeinvocation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_exit_evidence",
                        to="db.runattempt",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "agent_runtime_exit_evidence",
                "ordering": ("invocation_id", "created_at"),
                "indexes": [
                    models.Index(fields=("run", "created_at"), name="agent_rt_exit_run"),
                    models.Index(fields=("kind", "created_at"), name="agent_rt_exit_kind"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("final_sequence__gte", 0)), name="agent_rt_exit_seq_nonnegative"
                    ),
                ],
            },
        ),
        migrations.RunSQL(CREATE_RUNTIME_EVIDENCE_GUARDS, DROP_RUNTIME_EVIDENCE_GUARDS),
    ]
