# Generated by Django 5.2.15 on 2026-08-05 10:55

import django.db.models.deletion
import plane.db.models.agent
import uuid
from django.conf import settings
from django.db import migrations, models


CREATE_AGENT_REVISION_GUARDS = """
CREATE OR REPLACE FUNCTION reject_agent_revision_mutation() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'Agent revision history is immutable'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER agent_memory_revision_immutable
BEFORE UPDATE OR DELETE ON agent_memory_revisions
FOR EACH ROW
EXECUTE FUNCTION reject_agent_revision_mutation();

CREATE TRIGGER agent_memory_revision_immutable_truncate
BEFORE TRUNCATE ON agent_memory_revisions
FOR EACH STATEMENT
EXECUTE FUNCTION reject_agent_revision_mutation();

CREATE TRIGGER agent_skill_revision_immutable
BEFORE UPDATE OR DELETE ON agent_skill_revisions
FOR EACH ROW
EXECUTE FUNCTION reject_agent_revision_mutation();

CREATE TRIGGER agent_skill_revision_immutable_truncate
BEFORE TRUNCATE ON agent_skill_revisions
FOR EACH STATEMENT
EXECUTE FUNCTION reject_agent_revision_mutation();
"""

DROP_AGENT_REVISION_GUARDS = """
DROP TRIGGER IF EXISTS agent_memory_revision_immutable ON agent_memory_revisions;
DROP TRIGGER IF EXISTS agent_memory_revision_immutable_truncate ON agent_memory_revisions;
DROP TRIGGER IF EXISTS agent_skill_revision_immutable ON agent_skill_revisions;
DROP TRIGGER IF EXISTS agent_skill_revision_immutable_truncate ON agent_skill_revisions;
DROP FUNCTION IF EXISTS reject_agent_revision_mutation();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0130_agent_runtime_ingress_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemoryEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('fact', 'Fact'), ('preference', 'Preference')], default='fact', max_length=32)),
                ('visibility', models.CharField(choices=[('agent_private', 'Agent private'), ('subject_user', 'Subject user')], default='agent_private', max_length=32)),
                ('retention_expires_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memory_entries', to='db.agentactor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_memory_deletions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_%(class)s', to='db.project')),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_memory_entries', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_memory_entries',
                'ordering': ('key', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='AgentMemoryRevision',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('revision', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('candidate', 'Candidate'), ('active', 'Active')], max_length=32)),
                ('content', models.TextField()),
                ('content_digest', models.CharField(editable=False, max_length=72)),
                ('provenance', models.CharField(choices=[('human', 'Human'), ('agent_learning', 'Agent learning'), ('gardener', 'Gardener'), ('rollback', 'Rollback'), ('imported', 'Imported'), ('runtime', 'Runtime')], max_length=32)),
                ('provenance_ref', models.CharField(blank=True, max_length=255)),
                ('rationale', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='db.agentmemoryentry')),
                ('predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='db.agentmemoryrevision')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_%(class)s', to='db.project')),
                ('source_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_revision_sources', to='db.agentactor')),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_revision_sources', to='db.runattempt')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_memory_revisions',
                'ordering': ('entry_id', 'revision'),
            },
        ),
        migrations.CreateModel(
            name='AgentSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('cron_expression', models.CharField(max_length=255)),
                ('timezone_name', models.CharField(default='UTC', max_length=64)),
                ('target_ref', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('acceptance_criteria', models.JSONField(default=plane.db.models.agent.default_list)),
                ('context_refs', models.JSONField(default=plane.db.models.agent.default_list)),
                ('retry_policy', models.JSONField(default=plane.db.models.agent.default_dict)),
                ('state', models.CharField(choices=[('enabled', 'Enabled'), ('paused', 'Paused'), ('disabled', 'Disabled')], default='enabled', max_length=32)),
                ('next_fire_at', models.DateTimeField(blank=True, null=True)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='db.agentactor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_schedules',
                'ordering': ('next_fire_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AgentScheduleFire',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('scheduled_for', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('created', 'Assignment created'), ('failed', 'Failed'), ('exhausted', 'Retries exhausted')], default='pending', max_length=32)),
                ('error', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('fired_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_fire', to='db.assignmentcontract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_%(class)s', to='db.project')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fires', to='db.agentschedule')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_schedule_fires',
                'ordering': ('-scheduled_for',),
            },
        ),
        migrations.CreateModel(
            name='AgentSkillDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('agent_private', 'Agent private'), ('subject_user', 'Subject user'), ('template', 'Template'), ('workspace', 'Workspace'), ('organization', 'Organization')], default='agent_private', max_length=32)),
                ('retention_expires_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_definitions', to='db.agentactor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_skill_deletions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_%(class)s', to='db.project')),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_skill_definitions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_skill_definitions',
                'ordering': ('key', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='AgentSkillRevision',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('revision', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('candidate', 'Candidate'), ('active', 'Active')], max_length=32)),
                ('package_files', models.JSONField(default=plane.db.models.agent.default_dict)),
                ('package_digest', models.CharField(editable=False, max_length=72)),
                ('provenance', models.CharField(choices=[('human', 'Human'), ('agent_learning', 'Agent learning'), ('gardener', 'Gardener'), ('rollback', 'Rollback'), ('imported', 'Imported'), ('runtime', 'Runtime')], max_length=32)),
                ('provenance_ref', models.CharField(blank=True, max_length=255)),
                ('rationale', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='db.agentskilldefinition')),
                ('predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='db.agentskillrevision')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_%(class)s', to='db.project')),
                ('source_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_revision_sources', to='db.agentactor')),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_revision_sources', to='db.runattempt')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_skill_revisions',
                'ordering': ('definition_id', 'revision'),
            },
        ),
        migrations.CreateModel(
            name='AgentChangeProposal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('kind', models.CharField(choices=[('memory', 'Memory'), ('skill', 'Skill')], max_length=32)),
                ('state', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied')], default='proposed', max_length=32)),
                ('rationale', models.TextField()),
                ('requested_visibility', models.CharField(blank=True, max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('applied_revision_ref', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('command_fingerprint', models.CharField(blank=True, editable=False, max_length=72, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_proposals', to='db.agentactor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_%(class)s', to='db.project')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gardener_proposals', to='db.agentactor')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_change_reviews', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_%(class)s', to='db.workspace')),
                ('memory_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='db.agentmemoryrevision')),
                ('skill_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='db.agentskillrevision')),
            ],
            options={
                'db_table': 'agent_change_proposals',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='agentmemoryentry',
            constraint=models.CheckConstraint(condition=models.Q(('key', ''), _negated=True), name='agent_memory_key_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='agentmemoryentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('subject_user__isnull', True), ('visibility', 'agent_private')), models.Q(('subject_user__isnull', False), ('visibility', 'subject_user')), _connector='OR'), name='agent_memory_visibility_subject_binding'),
        ),
        migrations.AddConstraint(
            model_name='agentmemoryentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'preference'), ('visibility', 'subject_user')), models.Q(('kind', 'fact'), ('visibility', 'agent_private')), models.Q(('kind', 'preference'), ('visibility', 'agent_private')), _connector='OR'), name='agent_memory_preference_visibility'),
        ),
        migrations.AddConstraint(
            model_name='agentmemoryentry',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('visibility', 'agent_private')), fields=('actor', 'key'), name='agent_memory_unique_private_key'),
        ),
        migrations.AddConstraint(
            model_name='agentmemoryentry',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('visibility', 'subject_user')), fields=('actor', 'key', 'subject_user'), name='agent_memory_unique_subject_key'),
        ),
        migrations.AddConstraint(
            model_name='agentmemoryrevision',
            constraint=models.UniqueConstraint(fields=('entry', 'revision'), name='agent_memory_revision_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='agentmemoryrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='agent_memory_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='agentschedule',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='agent_schedule_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='agentschedule',
            constraint=models.CheckConstraint(condition=models.Q(('cron_expression', ''), _negated=True), name='agent_schedule_cron_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='agentschedulefire',
            constraint=models.UniqueConstraint(fields=('schedule', 'scheduled_for'), name='agent_schedule_fire_unique_slot'),
        ),
        migrations.AddConstraint(
            model_name='agentschedulefire',
            constraint=models.CheckConstraint(condition=models.Q(('attempt__gte', 1)), name='agent_schedule_fire_attempt_positive'),
        ),
        migrations.AddConstraint(
            model_name='agentskilldefinition',
            constraint=models.CheckConstraint(condition=models.Q(('key', ''), _negated=True), name='agent_skill_key_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='agentskilldefinition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('subject_user__isnull', True), ('visibility', 'agent_private')), models.Q(('subject_user__isnull', False), ('visibility', 'subject_user')), models.Q(('subject_user__isnull', True), ('visibility__in', ['template', 'workspace', 'organization'])), _connector='OR'), name='agent_skill_visibility_subject_binding'),
        ),
        migrations.AddConstraint(
            model_name='agentskilldefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('subject_user__isnull', True), ('visibility__in', ['template', 'workspace', 'organization'])), fields=('workspace', 'key'), name='agent_skill_unique_shared_key'),
        ),
        migrations.AddConstraint(
            model_name='agentskilldefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('subject_user__isnull', False)), fields=('actor', 'key', 'visibility', 'subject_user'), name='agent_skill_unique_subject_key'),
        ),
        migrations.AddConstraint(
            model_name='agentskillrevision',
            constraint=models.UniqueConstraint(fields=('definition', 'revision'), name='agent_skill_revision_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='agentskillrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='agent_skill_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='agentchangeproposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'memory'), ('memory_revision__isnull', False), ('skill_revision__isnull', True)), models.Q(('kind', 'skill'), ('memory_revision__isnull', True), ('skill_revision__isnull', False)), _connector='OR'), name='agent_proposal_one_revision_kind'),
        ),
        migrations.RunSQL(CREATE_AGENT_REVISION_GUARDS, DROP_AGENT_REVISION_GUARDS),
    ]
