# Generated by Django 5.2.15 on 2026-08-05

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models
import django.db.models.deletion

from plane.db.models.agent import default_dict


REPLACE_RUN_KEYED_BINDING_TRIGGER = """
DROP TRIGGER IF EXISTS agent_run_keyed_binding_guard ON agent_run_attempts;
CREATE TRIGGER agent_run_keyed_binding_guard
BEFORE UPDATE ON agent_run_attempts
FOR EACH ROW EXECUTE FUNCTION agent_guard_keyed_record_binding_immutable(
    'creation_idempotency_key',
    'command_fingerprint,deleted_at,updated_at,updated_by_id,state,invocation_count,last_invocation_id,cumulative_usage,code_mode_reserved_usage'
);
"""

RESTORE_RUN_KEYED_BINDING_TRIGGER = """
DROP TRIGGER IF EXISTS agent_run_keyed_binding_guard ON agent_run_attempts;
CREATE TRIGGER agent_run_keyed_binding_guard
BEFORE UPDATE ON agent_run_attempts
FOR EACH ROW EXECUTE FUNCTION agent_guard_keyed_record_binding_immutable(
    'creation_idempotency_key',
    'command_fingerprint,deleted_at,updated_at,updated_by_id,state,invocation_count,last_invocation_id,cumulative_usage'
);
"""

ENSURE_AGENT_PRINCIPAL_FIELD = """
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'agent_actors' AND column_name = 'principal_id'
    ) THEN
        ALTER TABLE agent_actors ADD COLUMN principal_id uuid;
    END IF;
    IF NOT EXISTS (
        SELECT 1
        FROM pg_index i
        JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = i.indkey[0]
        WHERE i.indrelid = 'agent_actors'::regclass
          AND i.indisunique
          AND i.indnkeyatts = 1
          AND a.attname = 'principal_id'
    ) THEN
        CREATE UNIQUE INDEX agent_actors_principal_id_key ON agent_actors (principal_id);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'agent_actors'::regclass
          AND confrelid = 'users'::regclass
          AND contype = 'f'
          AND conkey = ARRAY[
              (SELECT attnum FROM pg_attribute
               WHERE attrelid = 'agent_actors'::regclass AND attname = 'principal_id')
          ]::smallint[]
    ) THEN
        ALTER TABLE agent_actors
        ADD CONSTRAINT agent_actors_principal_id_fk
        FOREIGN KEY (principal_id) REFERENCES users (id)
        DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;
"""

ENSURE_CODE_MODE_RESERVATION_FIELD = """
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'agent_run_attempts' AND column_name = 'code_mode_reserved_usage'
    ) THEN
        ALTER TABLE agent_run_attempts
        ADD COLUMN code_mode_reserved_usage jsonb NOT NULL DEFAULT '{}'::jsonb;
    END IF;
END $$;
UPDATE agent_run_attempts SET code_mode_reserved_usage = '{}'::jsonb
WHERE code_mode_reserved_usage IS NULL;
ALTER TABLE agent_run_attempts ALTER COLUMN code_mode_reserved_usage SET NOT NULL;
ALTER TABLE agent_run_attempts ALTER COLUMN code_mode_reserved_usage DROP DEFAULT;
"""

REMOVE_AGENT_PRINCIPAL_FIELD = """
ALTER TABLE agent_actors DROP CONSTRAINT IF EXISTS agent_actors_principal_id_fk;
DROP INDEX IF EXISTS agent_actors_principal_id_key;
ALTER TABLE agent_actors DROP COLUMN IF EXISTS principal_id;
"""

REMOVE_CODE_MODE_RESERVATION_FIELD = """
ALTER TABLE agent_run_attempts DROP COLUMN IF EXISTS code_mode_reserved_usage;
"""


class AlterFieldIfAlreadyApplied(migrations.AlterField):
    """Make the non-null transition safe after a non-atomic retry."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.model_name)
        table = model._meta.db_table
        with schema_editor.connection.cursor() as cursor:
            columns = schema_editor.connection.introspection.get_table_description(cursor, table)
        current = next((column for column in columns if column.name == self.name), None)
        if current is not None and not current.null:
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


def provision_agent_principals(apps, schema_editor):
    AgentActor = apps.get_model("db", "AgentActor")
    User = apps.get_model("db", "User")
    WorkspaceMember = apps.get_model("db", "WorkspaceMember")
    ProjectMember = apps.get_model("db", "ProjectMember")

    for actor in AgentActor.objects.all().iterator():
        principal = None
        if actor.principal_id is None:
            identity = str(actor.pk).replace("-", "")
            principal, _ = User.objects.get_or_create(
                username=f"plane_agent_{identity}",
                defaults={
                    "email": f"plane-agent-{identity}@plane.internal",
                    "display_name": actor.display_name,
                    "is_bot": True,
                    "is_active": True,
                    "is_password_autoset": True,
                    "password": make_password(None),
                },
            )
            actor.principal_id = principal.pk
            actor.save(update_fields=["principal"])
        else:
            principal = User.objects.get(pk=actor.principal_id)
        workspace_member, _ = WorkspaceMember.objects.get_or_create(
            workspace_id=actor.workspace_id,
            member_id=principal.pk,
            defaults={"role": 15, "is_active": True},
        )
        if not workspace_member.is_active:
            WorkspaceMember.objects.filter(pk=workspace_member.pk).update(is_active=True)
        if actor.project_id is not None:
            project_member, _ = ProjectMember.objects.get_or_create(
                workspace_id=actor.workspace_id,
                project_id=actor.project_id,
                member_id=principal.pk,
                defaults={"role": 15, "is_active": True},
            )
            if not project_member.is_active:
                ProjectMember.objects.filter(pk=project_member.pk).update(is_active=True)


def unprovision_agent_principals(apps, schema_editor):
    AgentActor = apps.get_model("db", "AgentActor")
    AgentActor.objects.update(principal=None)


class Migration(migrations.Migration):
    atomic = False
    dependencies = [("db", "0130_agent_runtime_ingress_evidence")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(ENSURE_AGENT_PRINCIPAL_FIELD, REMOVE_AGENT_PRINCIPAL_FIELD),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="agentactor",
                    name="principal",
                    field=models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plane_agent_actor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(ENSURE_CODE_MODE_RESERVATION_FIELD, REMOVE_CODE_MODE_RESERVATION_FIELD),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="runattempt",
                    name="code_mode_reserved_usage",
                    field=models.JSONField(default=default_dict),
                ),
            ],
        ),
        migrations.RunPython(provision_agent_principals, unprovision_agent_principals),
        AlterFieldIfAlreadyApplied(
            model_name="agentactor",
            name="principal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plane_agent_actor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunSQL(REPLACE_RUN_KEYED_BINDING_TRIGGER, RESTORE_RUN_KEYED_BINDING_TRIGGER),
        migrations.AlterField(
            model_name="runinputevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("human_input", "Human input"),
                    ("continuation", "Continuation"),
                    ("code_mode_usage", "Code Mode usage"),
                ],
                max_length=32,
            ),
        ),
    ]
