# Generated by Django 5.2.15 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0130_agent_runtime_ingress_evidence")]

    operations = [
        migrations.AddField(
            model_name="runattempt",
            name="pending_input_ref",
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
    ]
