# Generated by Django 5.2.15 on 2026-08-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0131_agentmemoryentry_agentmemoryrevision_agentschedule_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agentskilldefinition',
            name='agent_skill_visibility_subject_binding',
        ),
        migrations.RemoveConstraint(
            model_name='agentskilldefinition',
            name='agent_skill_unique_shared_key',
        ),
        migrations.AddField(
            model_name='agentchangeproposal',
            name='requested_scope_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentskilldefinition',
            name='shared_scope_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='agentmemoryrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('provenance', 'rollback')), fields=('entry', 'provenance', 'provenance_ref'), name='agent_memory_revision_unique_rollback_target'),
        ),
        migrations.AddConstraint(
            model_name='agentskilldefinition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('shared_scope_id__isnull', True), ('subject_user__isnull', True), ('visibility', 'agent_private')), models.Q(('shared_scope_id__isnull', True), ('subject_user__isnull', False), ('visibility', 'subject_user')), models.Q(('shared_scope_id__isnull', False), ('subject_user__isnull', True), ('visibility', 'workspace')), _connector='OR'), name='agent_skill_visibility_scope_binding'),
        ),
        migrations.AddConstraint(
            model_name='agentskilldefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('visibility', 'workspace')), fields=('shared_scope_id', 'key'), name='agent_skill_unique_shared_key'),
        ),
        migrations.AddConstraint(
            model_name='agentskillrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('provenance', 'rollback')), fields=('definition', 'provenance', 'provenance_ref'), name='agent_skill_revision_unique_rollback_target'),
        ),
    ]
