# Generated by Django 5.2.15 on 2026-08-05 11:56

from django.db import migrations, models
from django.db.models import F


_UNSUPPORTED_SHARED_VISIBILITIES = ("template", "organization")


def _preflight_unsupported_legacy_scopes(apps, schema_editor):
    """Reject legacy scopes before 0132 changes schema or data.

    Plane has no authoritative template or organization owner yet. Those rows
    cannot be safely mapped to a workspace, so the migration must stop before
    dropping the 0131 constraints or adding the new scope columns.
    """

    skill_model = apps.get_model("db", "AgentSkillDefinition")
    proposal_model = apps.get_model("db", "AgentChangeProposal")
    skills = list(
        skill_model.objects.filter(visibility__in=_UNSUPPORTED_SHARED_VISIBILITIES).values_list(
            "id", "visibility", "workspace_id"
        )[:20]
    )
    proposals = list(
        proposal_model.objects.filter(requested_visibility__in=_UNSUPPORTED_SHARED_VISIBILITIES).values_list(
            "id", "requested_visibility", "workspace_id"
        )[:20]
    )
    if skills or proposals:
        raise RuntimeError(
            "0132 cannot migrate unsupported template/organization skill scopes; "
            "reclassify or remove these rows with an authoritative owner before retrying. "
            f"legacy skills={skills!r}; legacy proposals={proposals!r}"
        )


def _backfill_supported_scopes(apps, schema_editor):
    """Reconstruct supported scope IDs from their authoritative workspace IDs.

    0131 had no physical scope columns. Workspace scope is intentionally
    functionally determined by each row's workspace_id, so this is lossless
    after a 0132 -> 0131 -> 0132 round trip. Private and subject-user rows are
    not touched.
    """

    skill_model = apps.get_model("db", "AgentSkillDefinition")
    proposal_model = apps.get_model("db", "AgentChangeProposal")
    skill_model.objects.filter(visibility="workspace").update(shared_scope_id=F("workspace_id"))
    proposal_model.objects.filter(kind="skill", requested_visibility="workspace").update(
        requested_scope_id=F("workspace_id")
    )


class Migration(migrations.Migration):
    # PostgreSQL applies this migration transactionally. A failed preflight or
    # constraint application therefore rolls back schema and backfill together;
    # a retry sees the original 0131 state. Reversal removes fields that 0131
    # cannot represent, but forward reconstruction restores supported workspace
    # scopes exactly from workspace_id rather than aliasing unsupported scopes.
    atomic = True

    dependencies = [
        ("db", "0131_agentmemoryentry_agentmemoryrevision_agentschedule_and_more"),
    ]

    operations = [
        migrations.RunPython(_preflight_unsupported_legacy_scopes, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="agentskilldefinition",
            name="agent_skill_visibility_subject_binding",
        ),
        migrations.RemoveConstraint(
            model_name="agentskilldefinition",
            name="agent_skill_unique_shared_key",
        ),
        migrations.AddField(
            model_name="agentchangeproposal",
            name="requested_scope_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentskilldefinition",
            name="shared_scope_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(_backfill_supported_scopes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="agentmemoryrevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provenance", "rollback")),
                fields=("entry", "provenance", "provenance_ref"),
                name="agent_memory_revision_unique_rollback_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentskilldefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("shared_scope_id__isnull", True),
                        ("subject_user__isnull", True),
                        ("visibility", "agent_private"),
                    ),
                    models.Q(
                        ("shared_scope_id__isnull", True),
                        ("subject_user__isnull", False),
                        ("visibility", "subject_user"),
                    ),
                    models.Q(
                        ("shared_scope_id__isnull", False), ("subject_user__isnull", True), ("visibility", "workspace")
                    ),
                    _connector="OR",
                ),
                name="agent_skill_visibility_scope_binding",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentskilldefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("visibility", "workspace")),
                fields=("shared_scope_id", "key"),
                name="agent_skill_unique_shared_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentskillrevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provenance", "rollback")),
                fields=("definition", "provenance", "provenance_ref"),
                name="agent_skill_revision_unique_rollback_target",
            ),
        ),
    ]
