# Generated by Django 5.2.15 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0131_run_pending_input_reference")]

    operations = [
        migrations.AddField(
            model_name="runinputevent",
            name="sequence",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="runinputevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(sequence__isnull=False),
                fields=("run", "sequence"),
                name="agent_input_run_sequence_unique",
            ),
        ),
    ]
