# Generated by Django 5.2.15 on 2026-08-05

from django.db import migrations, models


SEQUENCE_BACKFILL_SQL = """
LOCK TABLE agent_run_input_events IN SHARE ROW EXCLUSIVE MODE;
WITH ranked AS (
    SELECT id,
           row_number() OVER (PARTITION BY run_id ORDER BY created_at, id)::integer AS sequence
    FROM agent_run_input_events
)
UPDATE agent_run_input_events AS event
SET sequence = ranked.sequence
FROM ranked
WHERE event.id = ranked.id;
"""


SEQUENCE_BACKFILL_REVERSE_SQL = """
-- Reversal retains deterministic sequence values; the next forward migration
-- recomputes every row while holding the same table lock.
"""


GUARD_FORWARD_SQL = """
CREATE OR REPLACE FUNCTION agent_guard_keyed_record_binding_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    is_keyed boolean;
    excluded_columns text[];
BEGIN
    EXECUTE format('SELECT ($1).%I IS NOT NULL', TG_ARGV[0])
    INTO is_keyed
    USING OLD;
    IF NOT is_keyed THEN
        RETURN NEW;
    END IF;
    excluded_columns := string_to_array(TG_ARGV[1], ',');
    IF (to_jsonb(NEW) - excluded_columns) IS DISTINCT FROM (to_jsonb(OLD) - excluded_columns) THEN
        RAISE EXCEPTION 'Idempotency-bound Agent record fields are immutable'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS agent_run_keyed_binding_guard ON agent_run_attempts;
CREATE TRIGGER agent_run_keyed_binding_guard
BEFORE UPDATE ON agent_run_attempts
FOR EACH ROW EXECUTE FUNCTION agent_guard_keyed_record_binding_immutable(
    'creation_idempotency_key',
    'command_fingerprint,deleted_at,updated_at,updated_by_id,state,pending_input_ref,invocation_count,last_invocation_id,cumulative_usage'
);

CREATE OR REPLACE FUNCTION agent_guard_input_sequence_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.sequence IS DISTINCT FROM OLD.sequence THEN
        RAISE EXCEPTION 'RunInputEvent sequence is immutable'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER agent_input_sequence_immutable_guard
BEFORE UPDATE ON agent_run_input_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_input_sequence_immutable();
"""


GUARD_REVERSE_SQL = """
DROP TRIGGER IF EXISTS agent_input_sequence_immutable_guard ON agent_run_input_events;
DROP FUNCTION IF EXISTS agent_guard_input_sequence_immutable();
DROP TRIGGER IF EXISTS agent_run_keyed_binding_guard ON agent_run_attempts;
CREATE TRIGGER agent_run_keyed_binding_guard
BEFORE UPDATE ON agent_run_attempts
FOR EACH ROW EXECUTE FUNCTION agent_guard_keyed_record_binding_immutable(
    'creation_idempotency_key',
    'command_fingerprint,deleted_at,updated_at,updated_by_id,state,invocation_count,last_invocation_id,cumulative_usage'
);
"""


class Migration(migrations.Migration):
    dependencies = [("db", "0132_agent_input_event_sequence")]

    operations = [
        migrations.RemoveConstraint(
            model_name="runinputevent",
            name="agent_input_run_sequence_unique",
        ),
        migrations.RunSQL(SEQUENCE_BACKFILL_SQL, SEQUENCE_BACKFILL_REVERSE_SQL),
        migrations.AlterField(
            model_name="runinputevent",
            name="sequence",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AddConstraint(
            model_name="runinputevent",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence"),
                name="agent_input_run_sequence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="runinputevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(pending_input_ref__isnull=False),
                fields=("run", "pending_input_ref"),
                name="agent_input_run_pending_ref_unique",
            ),
        ),
        migrations.RunSQL(GUARD_FORWARD_SQL, GUARD_REVERSE_SQL),
    ]
