# Generated by Django 5.2.15 on 2026-08-05

from django.db import migrations, models


SEQUENCE_METADATA_FORWARD_SQL = """
CREATE TABLE agent_run_input_sequence_legacy_metadata (
    run_input_event_id uuid PRIMARY KEY REFERENCES agent_run_input_events(id) ON DELETE CASCADE,
    original_sequence integer NOT NULL,
    original_sequence_was_null boolean NOT NULL,
    CONSTRAINT agent_input_sequence_metadata_bounds CHECK (
        original_sequence >= 0
        AND original_sequence <= 2147483647
        AND (
            (original_sequence_was_null AND original_sequence = 0)
            OR NOT original_sequence_was_null
        )
    )
);

INSERT INTO agent_run_input_sequence_legacy_metadata (
    run_input_event_id, original_sequence, original_sequence_was_null
)
SELECT id, COALESCE(sequence, 0), sequence IS NULL
FROM agent_run_input_events;

CREATE OR REPLACE FUNCTION agent_guard_input_sequence_metadata_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'RunInputEvent migration metadata is immutable'
        USING ERRCODE = 'check_violation';
END;
$$;

DROP TRIGGER IF EXISTS agent_input_sequence_metadata_immutable_guard
    ON agent_run_input_sequence_legacy_metadata;
CREATE TRIGGER agent_input_sequence_metadata_immutable_guard
BEFORE UPDATE OR DELETE ON agent_run_input_sequence_legacy_metadata
FOR EACH ROW EXECUTE FUNCTION agent_guard_input_sequence_metadata_immutable();

REVOKE ALL ON TABLE agent_run_input_sequence_legacy_metadata FROM PUBLIC;
REVOKE ALL ON FUNCTION agent_guard_input_sequence_metadata_immutable() FROM PUBLIC;
"""


SEQUENCE_METADATA_REVERSE_SQL = """
DROP TRIGGER IF EXISTS agent_input_keyed_binding_guard ON agent_run_input_events;
DROP TRIGGER IF EXISTS agent_input_sequence_immutable_guard ON agent_run_input_events;

ALTER TABLE agent_run_input_events ALTER COLUMN sequence DROP NOT NULL;

UPDATE agent_run_input_events
SET sequence = NULL;

UPDATE agent_run_input_events AS event
SET sequence = CASE
    WHEN metadata.original_sequence_was_null THEN NULL
    ELSE metadata.original_sequence
END
FROM agent_run_input_sequence_legacy_metadata AS metadata
WHERE event.id = metadata.run_input_event_id;

DROP TRIGGER IF EXISTS agent_input_sequence_metadata_immutable_guard
    ON agent_run_input_sequence_legacy_metadata;
DROP FUNCTION IF EXISTS agent_guard_input_sequence_metadata_immutable();
DROP TABLE agent_run_input_sequence_legacy_metadata;
"""


LEGACY_INPUT_DISPOSITION_SQL = """
LOCK TABLE agent_run_input_events IN SHARE ROW EXCLUSIVE MODE;
DROP TRIGGER IF EXISTS agent_input_keyed_binding_guard ON agent_run_input_events;
WITH ranked AS (
    SELECT id,
           pending_input_ref,
           row_number() OVER (
               PARTITION BY run_id
               ORDER BY sequence NULLS LAST, created_at, id
           )::integer AS run_sequence,
           row_number() OVER (
               PARTITION BY run_id, pending_input_ref
               ORDER BY sequence NULLS LAST, created_at, id
           )::integer AS pending_rank
    FROM agent_run_input_events
)
UPDATE agent_run_input_events AS event
SET sequence = ranked.run_sequence,
    is_authoritative = ranked.pending_input_ref IS NULL OR ranked.pending_rank = 1
FROM ranked
WHERE event.id = ranked.id;
"""


INPUT_IMMUTABILITY_FORWARD_SQL = """
CREATE OR REPLACE FUNCTION agent_guard_input_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.workspace_id IS DISTINCT FROM OLD.workspace_id OR NEW.project_id IS DISTINCT FROM OLD.project_id
       OR NEW.run_id IS DISTINCT FROM OLD.run_id OR NEW.event_ref IS DISTINCT FROM OLD.event_ref
       OR NEW.kind IS DISTINCT FROM OLD.kind OR NEW.payload IS DISTINCT FROM OLD.payload
       OR NEW.payload_digest IS DISTINCT FROM OLD.payload_digest
       OR NEW.pending_input_ref IS DISTINCT FROM OLD.pending_input_ref
       OR NEW.is_authoritative IS DISTINCT FROM OLD.is_authoritative
       OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key THEN
        RAISE EXCEPTION 'RunInputEvent immutable fields cannot change' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS agent_input_immutable_guard ON agent_run_input_events;
CREATE TRIGGER agent_input_immutable_guard
BEFORE UPDATE ON agent_run_input_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_input_immutable();
"""


INPUT_IMMUTABILITY_REVERSE_SQL = """
CREATE OR REPLACE FUNCTION agent_guard_input_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.workspace_id IS DISTINCT FROM OLD.workspace_id OR NEW.project_id IS DISTINCT FROM OLD.project_id
       OR NEW.run_id IS DISTINCT FROM OLD.run_id OR NEW.event_ref IS DISTINCT FROM OLD.event_ref
       OR NEW.kind IS DISTINCT FROM OLD.kind OR NEW.payload IS DISTINCT FROM OLD.payload
       OR NEW.payload_digest IS DISTINCT FROM OLD.payload_digest
       OR NEW.pending_input_ref IS DISTINCT FROM OLD.pending_input_ref
       OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key THEN
        RAISE EXCEPTION 'RunInputEvent immutable fields cannot change' USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS agent_input_immutable_guard ON agent_run_input_events;
CREATE TRIGGER agent_input_immutable_guard
BEFORE UPDATE ON agent_run_input_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_input_immutable();
"""


KEYED_BINDING_FORWARD_SQL = """
CREATE OR REPLACE FUNCTION agent_guard_keyed_record_binding_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    is_keyed boolean;
    excluded_columns text[];
BEGIN
    EXECUTE format('SELECT ($1).%I IS NOT NULL', TG_ARGV[0])
    INTO is_keyed
    USING OLD;
    IF NOT is_keyed THEN
        RETURN NEW;
    END IF;
    excluded_columns := string_to_array(TG_ARGV[1], ',');
    IF (to_jsonb(NEW) - excluded_columns) IS DISTINCT FROM (to_jsonb(OLD) - excluded_columns) THEN
        RAISE EXCEPTION 'Idempotency-bound Agent record fields are immutable'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS agent_run_keyed_binding_guard ON agent_run_attempts;
CREATE TRIGGER agent_run_keyed_binding_guard
BEFORE UPDATE ON agent_run_attempts
FOR EACH ROW EXECUTE FUNCTION agent_guard_keyed_record_binding_immutable(
    'creation_idempotency_key',
    'command_fingerprint,deleted_at,updated_at,updated_by_id,state,pending_input_ref,invocation_count,last_invocation_id,cumulative_usage'
);

DROP TRIGGER IF EXISTS agent_input_keyed_binding_guard ON agent_run_input_events;
CREATE TRIGGER agent_input_keyed_binding_guard
BEFORE UPDATE ON agent_run_input_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_keyed_record_binding_immutable(
    'idempotency_key', 'command_fingerprint,deleted_at,updated_at,updated_by_id'
);

DROP TRIGGER IF EXISTS agent_invocation_keyed_binding_guard ON agent_runtime_invocations;
CREATE TRIGGER agent_invocation_keyed_binding_guard
BEFORE UPDATE ON agent_runtime_invocations
FOR EACH ROW EXECUTE FUNCTION agent_guard_keyed_record_binding_immutable(
    'idempotency_key', 'command_fingerprint,deleted_at,updated_at,updated_by_id,state'
);

DROP TRIGGER IF EXISTS agent_outcome_keyed_binding_guard ON agent_outcome_submissions;
CREATE TRIGGER agent_outcome_keyed_binding_guard
BEFORE UPDATE ON agent_outcome_submissions
FOR EACH ROW EXECUTE FUNCTION agent_guard_keyed_record_binding_immutable(
    'submission_idempotency_key',
    'command_fingerprint,deleted_at,updated_at,updated_by_id,state,evaluator_id,evaluator_feedback,'
    'evaluator_reviewed_at,human_reviewer_id,human_decision_note,human_decided_at'
);

DROP TRIGGER IF EXISTS agent_terminal_keyed_binding_guard ON agent_run_terminal_events;
CREATE TRIGGER agent_terminal_keyed_binding_guard
BEFORE UPDATE ON agent_run_terminal_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_keyed_record_binding_immutable(
    'idempotency_key', 'command_fingerprint,deleted_at,updated_at,updated_by_id'
);

CREATE OR REPLACE FUNCTION agent_guard_input_sequence_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.sequence IS DISTINCT FROM OLD.sequence THEN
        RAISE EXCEPTION 'RunInputEvent sequence is immutable'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS agent_input_sequence_immutable_guard ON agent_run_input_events;
CREATE TRIGGER agent_input_sequence_immutable_guard
BEFORE UPDATE ON agent_run_input_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_input_sequence_immutable();
"""


KEYED_BINDING_REVERSE_SQL = """
DROP TRIGGER IF EXISTS agent_input_sequence_immutable_guard ON agent_run_input_events;
DROP FUNCTION IF EXISTS agent_guard_input_sequence_immutable();

DROP TRIGGER IF EXISTS agent_run_keyed_binding_guard ON agent_run_attempts;
CREATE TRIGGER agent_run_keyed_binding_guard
BEFORE UPDATE ON agent_run_attempts
FOR EACH ROW EXECUTE FUNCTION agent_guard_keyed_record_binding_immutable(
    'creation_idempotency_key',
    'command_fingerprint,deleted_at,updated_at,updated_by_id,state,invocation_count,last_invocation_id,cumulative_usage'
);

DROP TRIGGER IF EXISTS agent_input_keyed_binding_guard ON agent_run_input_events;
CREATE TRIGGER agent_input_keyed_binding_guard
BEFORE UPDATE ON agent_run_input_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_keyed_record_binding_immutable(
    'idempotency_key', 'command_fingerprint,deleted_at,updated_at,updated_by_id'
);

DROP TRIGGER IF EXISTS agent_invocation_keyed_binding_guard ON agent_runtime_invocations;
CREATE TRIGGER agent_invocation_keyed_binding_guard
BEFORE UPDATE ON agent_runtime_invocations
FOR EACH ROW EXECUTE FUNCTION agent_guard_keyed_record_binding_immutable(
    'idempotency_key', 'command_fingerprint,deleted_at,updated_at,updated_by_id,state'
);

DROP TRIGGER IF EXISTS agent_outcome_keyed_binding_guard ON agent_outcome_submissions;
CREATE TRIGGER agent_outcome_keyed_binding_guard
BEFORE UPDATE ON agent_outcome_submissions
FOR EACH ROW EXECUTE FUNCTION agent_guard_keyed_record_binding_immutable(
    'submission_idempotency_key',
    'command_fingerprint,deleted_at,updated_at,updated_by_id,state,evaluator_id,evaluator_feedback,'
    'evaluator_reviewed_at,human_reviewer_id,human_decision_note,human_decided_at'
);

DROP TRIGGER IF EXISTS agent_terminal_keyed_binding_guard ON agent_run_terminal_events;
CREATE TRIGGER agent_terminal_keyed_binding_guard
BEFORE UPDATE ON agent_run_terminal_events
FOR EACH ROW EXECUTE FUNCTION agent_guard_keyed_record_binding_immutable(
    'idempotency_key', 'command_fingerprint,deleted_at,updated_at,updated_by_id'
);
"""


class Migration(migrations.Migration):
    dependencies = [("db", "0134_agent_input_event_sequence")]

    operations = [
        migrations.RunSQL(migrations.RunSQL.noop, SEQUENCE_METADATA_REVERSE_SQL),
        migrations.RemoveConstraint(
            model_name="runinputevent",
            name="agent_input_run_sequence_unique",
        ),
        migrations.AddField(
            model_name="runinputevent",
            name="is_authoritative",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.RunSQL(SEQUENCE_METADATA_FORWARD_SQL, migrations.RunSQL.noop),
        migrations.RunSQL(
            LEGACY_INPUT_DISPOSITION_SQL,
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="runinputevent",
            name="sequence",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AddConstraint(
            model_name="runinputevent",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence"),
                name="agent_input_run_sequence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="runinputevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_authoritative=True, pending_input_ref__isnull=False),
                fields=("run", "pending_input_ref"),
                name="agent_input_run_pending_ref_unique",
            ),
        ),
        migrations.RunSQL(
            INPUT_IMMUTABILITY_FORWARD_SQL + KEYED_BINDING_FORWARD_SQL,
            INPUT_IMMUTABILITY_REVERSE_SQL + KEYED_BINDING_REVERSE_SQL,
        ),
    ]
