# Generated by Django 5.2.15 on 2026-08-06

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from plane.db.models.agent import default_dict


REPLACE_USAGE_AGGREGATE_GUARDS = """
CREATE OR REPLACE FUNCTION agent_guard_run_lifecycle() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    expected_usage jsonb;
BEGIN
    IF NEW.invocation_count IS DISTINCT FROM OLD.invocation_count THEN
        IF NEW.invocation_count <> OLD.invocation_count + 1
           OR NEW.last_invocation_id IS NULL
           OR NOT EXISTS (
               SELECT 1 FROM agent_runtime_invocations i
               WHERE i.run_id = NEW.id AND i.invocation_id = NEW.last_invocation_id
           ) THEN
            RAISE EXCEPTION 'Run invocation lifecycle must advance one bound invocation at a time'
                USING ERRCODE = 'check_violation';
        END IF;
    ELSIF NEW.last_invocation_id IS DISTINCT FROM OLD.last_invocation_id THEN
        RAISE EXCEPTION 'Run invocation binding and usage changes require a new invocation'
            USING ERRCODE = 'check_violation';
    ELSIF NEW.cumulative_usage IS DISTINCT FROM OLD.cumulative_usage THEN
        SELECT jsonb_build_object(
                   'inputTokens',
                   COALESCE((SELECT sum((usage ->> 'inputTokens')::bigint)
                             FROM agent_runtime_invocations WHERE run_id = NEW.id), 0)
                   + COALESCE((SELECT sum((payload -> 'usage' ->> 'inputTokens')::bigint)
                               FROM agent_run_input_events
                               WHERE run_id = NEW.id AND kind = 'code_mode_usage'), 0)
                   + COALESCE((SELECT sum((usage ->> 'inputTokens')::bigint)
                               FROM agent_runtime_usage_observations
                               WHERE run_id = NEW.id), 0),
                   'outputTokens',
                   COALESCE((SELECT sum((usage ->> 'outputTokens')::bigint)
                             FROM agent_runtime_invocations WHERE run_id = NEW.id), 0)
                   + COALESCE((SELECT sum((payload -> 'usage' ->> 'outputTokens')::bigint)
                               FROM agent_run_input_events
                               WHERE run_id = NEW.id AND kind = 'code_mode_usage'), 0)
                   + COALESCE((SELECT sum((usage ->> 'outputTokens')::bigint)
                               FROM agent_runtime_usage_observations
                               WHERE run_id = NEW.id), 0),
                   'durationMs',
                   COALESCE((SELECT sum((usage ->> 'durationMs')::bigint)
                             FROM agent_runtime_invocations WHERE run_id = NEW.id), 0)
                   + COALESCE((SELECT sum((payload -> 'usage' ->> 'durationMs')::bigint)
                               FROM agent_run_input_events
                               WHERE run_id = NEW.id AND kind = 'code_mode_usage'), 0)
                   + COALESCE((SELECT sum((usage ->> 'durationMs')::bigint)
                               FROM agent_runtime_usage_observations
                               WHERE run_id = NEW.id), 0)
               )
        INTO expected_usage;
        IF NEW.cumulative_usage IS DISTINCT FROM expected_usage THEN
            RAISE EXCEPTION 'Run cumulative usage must equal invocation, runtime, and Code Mode usage facts'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION agent_check_run_invocation_aggregate() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    checked_run uuid;
    expected_count integer;
    expected_last text;
    expected_usage jsonb;
    actual_count integer;
    actual_usage jsonb;
BEGIN
    IF TG_TABLE_NAME = 'agent_runtime_invocations' THEN
        IF TG_OP = 'DELETE' THEN
            checked_run := OLD.run_id;
        ELSE
            checked_run := NEW.run_id;
        END IF;
    ELSE
        checked_run := NEW.id;
    END IF;
    SELECT invocation_count, last_invocation_id, cumulative_usage
    INTO expected_count, expected_last, expected_usage
    FROM agent_run_attempts
    WHERE id = checked_run;
    SELECT count(*)::integer,
           jsonb_build_object(
               'inputTokens',
               COALESCE(sum((usage ->> 'inputTokens')::bigint), 0)
               + COALESCE((SELECT sum((payload -> 'usage' ->> 'inputTokens')::bigint)
                           FROM agent_run_input_events
                           WHERE run_id = checked_run AND kind = 'code_mode_usage'), 0)
               + COALESCE((SELECT sum((usage ->> 'inputTokens')::bigint)
                           FROM agent_runtime_usage_observations
                           WHERE run_id = checked_run), 0),
               'outputTokens',
               COALESCE(sum((usage ->> 'outputTokens')::bigint), 0)
               + COALESCE((SELECT sum((payload -> 'usage' ->> 'outputTokens')::bigint)
                           FROM agent_run_input_events
                           WHERE run_id = checked_run AND kind = 'code_mode_usage'), 0)
               + COALESCE((SELECT sum((usage ->> 'outputTokens')::bigint)
                           FROM agent_runtime_usage_observations
                           WHERE run_id = checked_run), 0),
               'durationMs',
               COALESCE(sum((usage ->> 'durationMs')::bigint), 0)
               + COALESCE((SELECT sum((payload -> 'usage' ->> 'durationMs')::bigint)
                           FROM agent_run_input_events
                           WHERE run_id = checked_run AND kind = 'code_mode_usage'), 0)
               + COALESCE((SELECT sum((usage ->> 'durationMs')::bigint)
                           FROM agent_runtime_usage_observations
                           WHERE run_id = checked_run), 0)
           )
    INTO actual_count, actual_usage
    FROM agent_runtime_invocations
    WHERE run_id = checked_run;
    IF expected_count IS NULL
       OR expected_count <> actual_count
       OR expected_usage IS DISTINCT FROM actual_usage
       OR (expected_count = 0 AND expected_last IS NOT NULL)
       OR (expected_count > 0 AND NOT EXISTS (
           SELECT 1 FROM agent_runtime_invocations
           WHERE run_id = checked_run AND ordinal = expected_count
             AND invocation_id = expected_last
       )) THEN
        RAISE EXCEPTION 'Run invocation count and cumulative usage must equal the invocation aggregate'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END;
$$;
"""

RUNTIME_USAGE_APPEND_ONLY = """
CREATE OR REPLACE FUNCTION agent_runtime_usage_observation_append_only()
RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'runtime usage observations are append-only'
        USING ERRCODE = '55000';
END;
$$;
CREATE TRIGGER agent_runtime_usage_observation_append_only
BEFORE UPDATE OR DELETE ON agent_runtime_usage_observations
FOR EACH ROW EXECUTE FUNCTION agent_runtime_usage_observation_append_only();
CREATE TRIGGER agent_runtime_usage_observation_append_only_truncate
BEFORE TRUNCATE ON agent_runtime_usage_observations
FOR EACH STATEMENT EXECUTE FUNCTION agent_runtime_usage_observation_append_only();
"""


def backfill_runtime_controls(apps, schema_editor):
    RuntimeInvocation = apps.get_model("db", "RuntimeInvocation")
    RuntimeInvocationControl = apps.get_model("db", "RuntimeInvocationControl")
    for invocation in RuntimeInvocation.objects.all().iterator():
        RuntimeInvocationControl.objects.get_or_create(
            invocation_id=invocation.pk,
            defaults={
                "workspace_id": invocation.workspace_id,
                "project_id": invocation.project_id,
            },
        )


class Migration(migrations.Migration):
    dependencies = [("db", "0136_agent_principal_and_code_mode_reservations")]

    operations = [
        migrations.CreateModel(
            name="RuntimeInvocationControl",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("leased", "Leased"),
                            ("outcome_unknown", "Outcome unknown"),
                            ("released", "Released"),
                        ],
                        default="available",
                        max_length=32,
                    ),
                ),
                ("lease_owner", models.CharField(blank=True, editable=False, max_length=128, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("dispatch_started_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("cancellation_requested_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("cancellation_reason", models.CharField(blank=True, default="", editable=False, max_length=4096)),
                ("outcome_unknown_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("failure_code", models.CharField(blank=True, default="", editable=False, max_length=64)),
                ("failure_reason", models.CharField(blank=True, default="", editable=False, max_length=4096)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "invocation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_control",
                        to="db.runtimeinvocation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="agent_%(class)s", to="db.workspace"
                    ),
                ),
            ],
            options={
                "db_table": "agent_runtime_invocation_controls",
                "indexes": [
                    models.Index(fields=("state", "lease_expires_at"), name="agent_rt_control_lease_idx"),
                    models.Index(fields=("workspace", "created_at"), name="agent_rt_control_workspace_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RuntimeUsageObservation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("usage", models.JSONField(default=default_dict, editable=False)),
                ("fingerprint", models.CharField(editable=False, max_length=72)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_usage_observations",
                        to="db.agentactor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "invocation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_usage_observation",
                        to="db.runtimeinvocation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_usage_observations",
                        to="db.runattempt",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="agent_%(class)s", to="db.workspace"
                    ),
                ),
            ],
            options={
                "db_table": "agent_runtime_usage_observations",
                "ordering": ("invocation_id", "created_at"),
                "indexes": [models.Index(fields=("run", "created_at"), name="agent_rt_usage_run_idx")],
            },
        ),
        migrations.RunPython(backfill_runtime_controls, migrations.RunPython.noop),
        migrations.RunSQL(REPLACE_USAGE_AGGREGATE_GUARDS, migrations.RunSQL.noop),
        migrations.RunSQL(RUNTIME_USAGE_APPEND_ONLY, migrations.RunSQL.noop),
    ]
