# Generated by Django 5.2.15 on 2026-08-06 01:00

import django.db.models.deletion
import plane.db.models.agent
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0137_runtime_supervisor_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentactor',
            name='chief_of_staff_for',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chief_of_staff_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentcontract',
            name='budget',
            field=models.JSONField(default=plane.db.models.agent.default_dict),
        ),
        migrations.AddField(
            model_name='assignmentcontract',
            name='delegated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegated_assignments', to='db.agentactor'),
        ),
        migrations.AddField(
            model_name='assignmentcontract',
            name='delegation_command_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=72, null=True),
        ),
        migrations.AddField(
            model_name='assignmentcontract',
            name='delegation_depth',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='assignmentcontract',
            name='delegation_key',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='assignmentcontract',
            name='root_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooted_children', to='db.assignmentcontract'),
        ),
        migrations.AddField(
            model_name='assignmentcontract',
            name='scope',
            field=models.JSONField(default=plane.db.models.agent.default_dict),
        ),
        migrations.CreateModel(
            name='EvaluatorReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('criteria', models.JSONField(default=plane.db.models.agent.default_list)),
                ('verdict', models.CharField(choices=[('accept', 'Accept recommendation'), ('revision_requested', 'Revision requested')], max_length=32)),
                ('recommendation', models.TextField()),
                ('provenance', models.JSONField(default=plane.db.models.agent.default_dict)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('command_fingerprint', models.CharField(editable=False, max_length=72)),
                ('reviewed_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluator_reviews', to='db.agentactor')),
                ('evaluator_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluator_reviews', to='db.profileversion')),
                ('outcome', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evaluator_review', to='db.outcomesubmission')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_%(class)s', to='db.project')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluator_reviews', to='db.runattempt')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_evaluator_reviews',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentHRProposal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('kind', models.CharField(choices=[('hire', 'Hire'), ('role_change', 'Role change'), ('suspend', 'Suspend'), ('retire', 'Retire'), ('reassign', 'Reassign'), ('chief_of_staff', 'Chief of staff provisioning')], max_length=32)),
                ('state', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='proposed', max_length=32)),
                ('requested_role', models.CharField(blank=True, choices=[('worker', 'Worker'), ('delegator', 'Delegator'), ('gardener', 'Gardener'), ('chief_of_staff', 'Chief of staff'), ('hr', 'HR'), ('evaluator', 'Evaluator'), ('custom', 'Custom')], max_length=32, null=True)),
                ('requested_display_name', models.CharField(blank=True, max_length=255)),
                ('requested_profile', models.JSONField(default=plane.db.models.agent.default_dict)),
                ('expected_state_fingerprint', models.CharField(blank=True, max_length=72)),
                ('rationale', models.TextField()),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('command_fingerprint', models.CharField(editable=False, max_length=72)),
                ('decision_idempotency_key', models.CharField(blank=True, editable=False, max_length=128, null=True, unique=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('applied_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_hr_proposals', to='db.agentactor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_%(class)s', to='db.project')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hr_proposals', to='db.agentactor')),
                ('requested_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hr_requested_assignments', to='db.agentactor')),
                ('requested_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_hr_requested_principals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_hr_decisions', to=settings.AUTH_USER_MODEL)),
                ('subject_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hr_subject_proposals', to='db.agentactor')),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_hr_proposals', to=settings.AUTH_USER_MODEL)),
                ('target_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hr_reassignment_proposals', to='db.assignmentcontract')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_hr_proposals',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workspace', 'state'], name='agent_hr_scope_state_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind', 'reassign'), ('target_assignment__isnull', False)), models.Q(('kind', 'reassign'), _negated=True), _connector='OR'), name='agent_hr_reassign_has_assignment')],
            },
        ),
    ]
