# Generated by Django 5.2.15 on 2026-08-09

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0141_operationgateway_quotas"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeProviderAttempt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("lease_id", models.CharField(editable=False, max_length=128)),
                ("provider", models.CharField(editable=False, max_length=64)),
                ("model", models.CharField(editable=False, max_length=256)),
                ("destination_host", models.CharField(editable=False, max_length=255)),
                ("destination_path", models.CharField(editable=False, max_length=1024)),
                ("request_id", models.CharField(editable=False, max_length=256)),
                ("idempotency_key", models.CharField(editable=False, max_length=128, unique=True)),
                ("sequence", models.PositiveIntegerField(editable=False)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("intent", "Intent recorded"),
                            ("started", "External request started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("outcome_unknown", "Outcome unknown"),
                        ],
                        default="intent",
                        editable=False,
                        max_length=24,
                    ),
                ),
                ("upstream_initiated", models.BooleanField(default=False, editable=False)),
                ("status_class", models.CharField(blank=True, default="", editable=False, max_length=16)),
                ("error_code", models.CharField(blank=True, default="", editable=False, max_length=64)),
                ("terminal_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("fingerprint", models.CharField(editable=False, max_length=72)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_provider_attempts",
                        to="db.agentactor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "invocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_attempts",
                        to="db.runtimeinvocation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_provider_attempts",
                        to="db.runattempt",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "agent_runtime_provider_attempts",
                "ordering": ("invocation_id", "sequence"),
                "indexes": [
                    models.Index(fields=("invocation", "terminal_at"), name="agent_rt_provider_active"),
                    models.Index(fields=("run", "created_at"), name="agent_rt_provider_run"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("invocation", "sequence"),
                        name="agent_rt_provider_inv_seq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1)),
                        name="agent_rt_provider_seq_positive",
                    ),
                ],
            },
        ),
    ]
