# Generated by Django 5.2.15 on 2026-08-21

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("db", "0144_provider_attempt_diagnostics")]

    operations = [
        migrations.CreateModel(
            name="RuntimeReconciliation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("state", models.CharField(choices=[("reconciled", "Reconciled")], max_length=24)),
                ("fresh_assignment_decision", models.CharField(choices=[("safe", "Safe"), ("unsafe", "Unsafe")], max_length=16)),
                ("outcome_ref", models.CharField(blank=True, editable=False, max_length=128, null=True)),
                ("publication_ref", models.CharField(blank=True, editable=False, max_length=128, null=True)),
                ("terminal_event_ref", models.CharField(blank=True, editable=False, max_length=128, null=True)),
                ("runtime_exit_ref", models.CharField(blank=True, editable=False, max_length=128, null=True)),
                ("evidence", models.JSONField(default=dict, editable=False)),
                ("idempotency_key", models.CharField(editable=False, max_length=128, unique=True)),
                ("command_fingerprint", models.CharField(editable=False, max_length=72)),
                ("reconciled_at", models.DateTimeField(editable=False)),
                ("invocation", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="reconciliation", to="db.runtimeinvocation")),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="agent_runtimereconciliation", to="db.project")),
                ("reconciled_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="agent_runtime_reconciliations", to=settings.AUTH_USER_MODEL)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reconciliations", to="db.runattempt")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_runtimereconciliation", to="db.workspace")),
            ],
            options={"db_table": "agent_runtime_reconciliations", "ordering": ("-created_at",)},
        ),
        migrations.AddConstraint(
            model_name="runtimereconciliation",
            constraint=models.UniqueConstraint(fields=("run", "invocation"), name="agent_reconciliation_run_invocation_unique"),
        ),
    ]
