# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only

from django.urls import path

from plane.api.views.agent_admin import (
    AgentActorAdminDetailAPIEndpoint,
    AgentActorAdminListCreateAPIEndpoint,
    AgentAssignmentAdminDetailAPIEndpoint,
    AgentAssignmentAdminListCreateAPIEndpoint,
    AgentAssignmentCancelAPIEndpoint,
    AgentAssignmentDispatchAPIEndpoint,
    AgentGatewayReadbackDetailAPIEndpoint,
    AgentGatewayReadbackListAPIEndpoint,
    AgentGovernanceCommandAPIEndpoint,
    AgentGovernanceReadbackAPIEndpoint,
    AgentOperatorCanaryAPIEndpoint,
    AgentOperatorHealthAPIEndpoint,
    AgentOperatorReadbackAPIEndpoint,
    AgentOperatorSafetyStopAPIEndpoint,
    AgentOutcomeAcceptAPIEndpoint,
    AgentOutcomeAdminCreateAPIEndpoint,
    AgentOutcomeAdminDetailAPIEndpoint,
    AgentOutcomeRevisionAPIEndpoint,
    AgentOutcomeReviewAPIEndpoint,
    AgentProfileVersionAdminListCreateAPIEndpoint,
    AgentProfileVersionAdminDetailAPIEndpoint,
    AgentRunAdminDetailAPIEndpoint,
    AgentRunCancelAPIEndpoint,
    AgentRunInputEventAdminListCreateAPIEndpoint,
    AgentRunInvocationAdminListCreateAPIEndpoint,
)
from plane.api.views.agent_context_admin import (
    AgentMemoryAdminListCreateAPIEndpoint,
    AgentMemoryProposalAdminCreateAPIEndpoint,
    AgentMemoryRevisionAdminListAPIEndpoint,
    AgentMemoryRollbackAPIEndpoint,
    AgentProposalAdminListAPIEndpoint,
    AgentProposalPromoteAPIEndpoint,
    AgentProposalReviewAPIEndpoint,
    AgentScheduleAdminListCreateAPIEndpoint,
    AgentScheduleControlAPIEndpoint,
    AgentScheduleFireListAPIEndpoint,
    AgentScheduleFireRetryAPIEndpoint,
    AgentSkillAdminListCreateAPIEndpoint,
    AgentSkillProposalAdminCreateAPIEndpoint,
    AgentSkillRevisionAdminListAPIEndpoint,
    AgentSkillRollbackAPIEndpoint,
)
from plane.api.views.agent_catalog_admin import AgentGatewayCatalogAPIEndpoint, AgentGatewayStatusAPIEndpoint
from plane.api.views.agent_context_readback import AgentContextReadbackAPIEndpoint


urlpatterns = [
    path(
        "workspaces/<str:slug>/agent-admin/actors/",
        AgentActorAdminListCreateAPIEndpoint.as_view(http_method_names=["get", "post"]),
        name="agent-admin-actors",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/actors/<uuid:pk>/",
        AgentActorAdminDetailAPIEndpoint.as_view(http_method_names=["get", "patch"]),
        name="agent-admin-actor",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/actors/<uuid:actor_id>/profiles/",
        AgentProfileVersionAdminListCreateAPIEndpoint.as_view(http_method_names=["get", "post"]),
        name="agent-admin-profiles",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/actors/<uuid:actor_id>/profiles/<uuid:pk>/",
        AgentProfileVersionAdminDetailAPIEndpoint.as_view(http_method_names=["get"]),
        name="agent-admin-profile",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/actors/<uuid:actor_id>/assignments/",
        AgentAssignmentAdminListCreateAPIEndpoint.as_view(http_method_names=["get", "post"]),
        name="agent-admin-assignments",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/assignments/<uuid:pk>/",
        AgentAssignmentAdminDetailAPIEndpoint.as_view(http_method_names=["get"]),
        name="agent-admin-assignment",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/assignments/<uuid:assignment_id>/cancel/",
        AgentAssignmentCancelAPIEndpoint.as_view(http_method_names=["post"]),
        name="agent-admin-assignment-cancel",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/assignments/<uuid:assignment_id>/dispatch/",
        AgentAssignmentDispatchAPIEndpoint.as_view(http_method_names=["post"]),
        name="agent-admin-assignment-dispatch",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/runs/<uuid:pk>/",
        AgentRunAdminDetailAPIEndpoint.as_view(http_method_names=["get"]),
        name="agent-admin-run",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/runs/<uuid:run_id>/input-events/",
        AgentRunInputEventAdminListCreateAPIEndpoint.as_view(http_method_names=["get", "post"]),
        name="agent-admin-run-input-events",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/runs/<uuid:run_id>/invocations/",
        AgentRunInvocationAdminListCreateAPIEndpoint.as_view(http_method_names=["get", "post"]),
        name="agent-admin-run-invocations",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/runs/<uuid:run_id>/cancel/",
        AgentRunCancelAPIEndpoint.as_view(http_method_names=["post"]),
        name="agent-admin-run-cancel",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/runs/<uuid:run_id>/outcome/",
        AgentOutcomeAdminCreateAPIEndpoint.as_view(http_method_names=["post"]),
        name="agent-admin-outcome-create",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/outcomes/<uuid:pk>/",
        AgentOutcomeAdminDetailAPIEndpoint.as_view(http_method_names=["get"]),
        name="agent-admin-outcome",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/outcomes/<uuid:pk>/review/",
        AgentOutcomeReviewAPIEndpoint.as_view(http_method_names=["post"]),
        name="agent-admin-outcome-review",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/outcomes/<uuid:pk>/accept/",
        AgentOutcomeAcceptAPIEndpoint.as_view(http_method_names=["post"]),
        name="agent-admin-outcome-accept",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/outcomes/<uuid:pk>/revise/",
        AgentOutcomeRevisionAPIEndpoint.as_view(http_method_names=["post"]),
        name="agent-admin-outcome-revise",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/gateway/readback/",
        AgentGatewayReadbackListAPIEndpoint.as_view(http_method_names=["get"]),
        name="agent-admin-gateway-readback",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/gateway/readback/<uuid:pk>/",
        AgentGatewayReadbackDetailAPIEndpoint.as_view(http_method_names=["get"]),
        name="agent-admin-gateway-receipt",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/governance/",
        AgentGovernanceReadbackAPIEndpoint.as_view(http_method_names=["get"]),
        name="agent-admin-governance-readback",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/governance/commands/",
        AgentGovernanceCommandAPIEndpoint.as_view(http_method_names=["post"]),
        name="agent-admin-governance-command",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/operator/readback/",
        AgentOperatorReadbackAPIEndpoint.as_view(http_method_names=["get"]),
        name="agent-admin-operator-readback",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/operator/health/",
        AgentOperatorHealthAPIEndpoint.as_view(http_method_names=["get"]),
        name="agent-admin-operator-health",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/operator/canary/",
        AgentOperatorCanaryAPIEndpoint.as_view(http_method_names=["get"]),
        name="agent-admin-operator-canary",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/operator/safety-stop/",
        AgentOperatorSafetyStopAPIEndpoint.as_view(http_method_names=["post"]),
        name="agent-admin-operator-safety-stop",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/actors/<uuid:actor_id>/memory/",
        AgentMemoryAdminListCreateAPIEndpoint.as_view(http_method_names=["get", "post"]),
        name="agent-admin-memory",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/actors/<uuid:actor_id>/memory/<uuid:memory_id>/revisions/",
        AgentMemoryRevisionAdminListAPIEndpoint.as_view(http_method_names=["get"]),
        name="agent-admin-memory-revisions",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/actors/<uuid:actor_id>/memory/<uuid:memory_id>/proposals/",
        AgentMemoryProposalAdminCreateAPIEndpoint.as_view(http_method_names=["post"]),
        name="agent-admin-memory-proposal",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/actors/<uuid:actor_id>/memory/<uuid:memory_id>/rollback/",
        AgentMemoryRollbackAPIEndpoint.as_view(http_method_names=["post"]),
        name="agent-admin-memory-rollback",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/actors/<uuid:actor_id>/skills/",
        AgentSkillAdminListCreateAPIEndpoint.as_view(http_method_names=["get", "post"]),
        name="agent-admin-skills",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/actors/<uuid:actor_id>/skills/<uuid:skill_id>/revisions/",
        AgentSkillRevisionAdminListAPIEndpoint.as_view(http_method_names=["get"]),
        name="agent-admin-skill-revisions",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/actors/<uuid:actor_id>/skills/<uuid:skill_id>/proposals/",
        AgentSkillProposalAdminCreateAPIEndpoint.as_view(http_method_names=["post"]),
        name="agent-admin-skill-proposal",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/actors/<uuid:actor_id>/skills/<uuid:skill_id>/rollback/",
        AgentSkillRollbackAPIEndpoint.as_view(http_method_names=["post"]),
        name="agent-admin-skill-rollback",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/proposals/",
        AgentProposalAdminListAPIEndpoint.as_view(http_method_names=["get"]),
        name="agent-admin-proposals",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/proposals/<uuid:pk>/review/",
        AgentProposalReviewAPIEndpoint.as_view(http_method_names=["post"]),
        name="agent-admin-proposal-review",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/proposals/<uuid:pk>/promote/",
        AgentProposalPromoteAPIEndpoint.as_view(http_method_names=["post"]),
        name="agent-admin-proposal-promote",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/actors/<uuid:actor_id>/schedules/",
        AgentScheduleAdminListCreateAPIEndpoint.as_view(http_method_names=["get", "post"]),
        name="agent-admin-schedules",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/schedules/<uuid:schedule_id>/fires/",
        AgentScheduleFireListAPIEndpoint.as_view(http_method_names=["get", "post"]),
        name="agent-admin-schedule-fires",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/schedules/<uuid:schedule_id>/control/",
        AgentScheduleControlAPIEndpoint.as_view(http_method_names=["post"]),
        name="agent-admin-schedule-control",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/schedule-fires/<uuid:pk>/retry/",
        AgentScheduleFireRetryAPIEndpoint.as_view(http_method_names=["post"]),
        name="agent-admin-schedule-fire-retry",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/gateway/status/",
        AgentGatewayStatusAPIEndpoint.as_view(http_method_names=["get"]),
        name="agent-admin-gateway-status",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/gateway/catalog/",
        AgentGatewayCatalogAPIEndpoint.as_view(http_method_names=["get"]),
        name="agent-admin-gateway-catalog",
    ),
    path(
        "workspaces/<str:slug>/agent-admin/actors/<uuid:actor_id>/context/",
        AgentContextReadbackAPIEndpoint.as_view(http_method_names=["get"]),
        name="agent-admin-context-readback",
    ),
]
