# Copyright (c) 2026-present Ngo Quoc Huy
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

"""The single cross-record lifecycle transition seam."""

from .services import (
    AgentDomainError,
    IdempotencyConflictError,
    InvalidTransitionError,
    RecoveryIntentRequiredError,
    TerminalEventRequiredError,
    accept_outcome,
    cancel_assignment,
    create_actor,
    create_assignment,
    create_profile,
    create_run,
    decide_hr_proposal,
    delegate_assignment,
    ensure_human_workspace_admin,
    finalize_invocation,
    finish_code_mode,
    lock_invocation_path,
    propose_outcome,
    propose_chief_of_staff,
    propose_hr_change,
    record_input_event,
    record_invocation,
    code_mode_reserved_totals,
    code_mode_usage_totals,
    reap_code_mode_reservations,
    reconcile_code_mode_usage,
    reconcile_runtime_usage,
    record_provider_attempt_notice,
    reconcile_provider_attempts,
    reconcile_outcome_unknown,
    provider_attempts_reconciled,
    reserve_code_mode_usage,
    request_revision,
    review_outcome,
    transition_run,
)

__all__ = [
    "AgentDomainError",
    "IdempotencyConflictError",
    "InvalidTransitionError",
    "RecoveryIntentRequiredError",
    "TerminalEventRequiredError",
    "accept_outcome",
    "cancel_assignment",
    "create_actor",
    "create_assignment",
    "create_profile",
    "create_run",
    "decide_hr_proposal",
    "delegate_assignment",
    "ensure_human_workspace_admin",
    "finalize_invocation",
    "finish_code_mode",
    "lock_invocation_path",
    "propose_outcome",
    "propose_chief_of_staff",
    "propose_hr_change",
    "record_input_event",
    "record_invocation",
    "code_mode_reserved_totals",
    "code_mode_usage_totals",
    "reap_code_mode_reservations",
    "reconcile_code_mode_usage",
    "reconcile_runtime_usage",
    "record_provider_attempt_notice",
    "reconcile_provider_attempts",
    "reconcile_outcome_unknown",
    "provider_attempts_reconciled",
    "reserve_code_mode_usage",
    "request_revision",
    "review_outcome",
    "transition_run",
]
